AllenInstitute/MIES

tools/publish-docs-on-github.sh
tools/send-github-message-build-finished.sh
tools/upload-github-release-asset.sh

http://bamboo.corp.alleninstitute.org/browse/MIES-CM-BUD-424 is already changed to use the public repo here. This are just some changes to make that even better.

Update ci scripts

---

Packages/MIES/MIES_WaveBuilder.ipf
Packages/Testing-MIES/UTF_WaveBuilder.ipf

Wavebuilder: Fix forgotten delta mode for pulse duration for pulse train pulses

---

Packages/MIES/MIES_DAEphys.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_TestNWBExportV1.ipf

Fix I Zero clamp mode usage

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf

Allow pressure tweaking with mouse wheel

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataConfiguratorITC.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_WaveBuilder.ipf

Use per trace pulse information in pulse average graph

---

Packages/MIES/MIES_DAEphys_Macro.ipf

Aligned and moved some controls in the DA_ephys panel. I used `reset and store current DA_ephys panel`. I did not version the panel.

DA_Ephys >> Data Acquisition >> Data Acquisition layout cleanup

---

UserConfig - Template.txt

216remove oodDAQ resolution from userConfig template file

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_OverlaySweeps.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_TestNWBExportV1.ipf

Add TTL stimsets to overlay sweeps

---

Packages/MIES/MIES_AnalysisFunctions.ipf
Packages/Testing-MIES/UTF_AnalysisFunctionManagement.ipf

We now allow the textwave to have multiple tuples of event/data. This
approach is backwards compatible.
Close #226.

SetControlInEvent: Make it possible to set the same control in multiple events

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf

Comment loading nwb

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/Testing-MIES/UTF_TestNWBExportV1.ipf

Scale ttl waves properly

---

.gitattributes
Packages/MIES/MIES_CheckInstallation.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_Menu.ipf
Packages/MIES/MIES_Utilities.ipf
tools/create-release.sh

Disable ASLR for ITC hardware

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_CheckInstallation.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataConfiguratorITC.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf

Enable tests for ITC 1600

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DataConfiguratorITC.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

@MichaelHuth Can you take a look if my changes make sense especially wrt to NI hardware?

Bugfix: Fix find level "level" threshold for PSQ_Ramp and NI hardware

---

Packages/MIES/MIES_GuiUtilities.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Close #298.
PGC_SetAndActivateControl is the wrong place to add it as that only works with real controls which have a GUI procedure attached.
I've added plain functions only therefore.

Add notebook text wrappers

---

tools/set-bamboo-job-result.sh

The latest bugfix to FilterIIR changed the output in our regression
tests.

RunAllTests.pxp: Update Wavebuilder stimsets using FilterIIR

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_ExperimentConfig.ipf
Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_IgorHooks.ipf
Packages/MIES/MIES_Pictures.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_TangoInteract.ipf
Packages/MIES_Include.ipf
Packages/Testing-MIES/UTF_AnalysisFunctionManagement.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_DAEphys.ipf
Packages/Testing-MIES/UTF_Epochs.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqDaScale.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqFastRheoEstimate.ipf
Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf
Packages/Testing-MIES/UTF_PatchSeqRamp.ipf
Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf
Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/Testing-MIES/UTF_VeryBasicHardwareTests.ipf

Rework itc list gathering

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfiguratorITC.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/Testing-MIES/UTF_WaveBuilder.ipf

Fix daq error with combined stimset

---

Packages/MIES/MIES_AnalysisFunctionManagement.ipf
Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/MIES/MIES_Oscilloscope.ipf
Packages/MIES/MIES_Structures.ipf
Packages/Testing-MIES/UserAnalysisFunctions.ipf
Packages/doc/analysis-functions-calls-during-RA-stages.svg

The entries lastKnownRowIndex/lastValidRowIndex were ill-defined for some events.
This PR fixes that and also adds some more tests.

More analysis function tests

---

Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_GuiState.ipf
Packages/MIES/MIES_SweepFormula.ipf

Fix Daephys comment handling

---

Packages/MIES/MIES_GuiUtilities.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Cooler restore cursors

---

Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DataConfiguratorITC.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_Utils.ipf

My TP caching did not work with NI hardware.
I've fixed that now and also added the missing test which should have been part of the original PR.

Fix ni tp md caching

---

tools/initial-repo-config.sh

Nicify git status

---

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/doc/conf.py

Fix getmiesversion

---

Packages/doc/developers.rst

We can have that PR open until the silent installation does what users expect.

developers.rst: Mention how to install silently

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_SweepFormula.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/doc/SweepFormula.rst

SweepFormula: Add findlevel operation

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_SweepFormula.ipf

The SweepFormula gets an enable button and is disabled b default to
allow omitting calculations on DB update.
Closes #347

Add enable/disable button to SF

---

Packages/MIES/MIES_Pictures.ipf

@timjarsky Ready to be merged if CI passes.

Update doxygen filter

---

Packages/MIES/MIES_Cache.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_OptimzedOverlapDistributedAcquisition.ipf
Packages/Testing-MIES/UTF_Utils.ipf

@MichaelHuth Any ideas for the fixing up buggy region data? This seems to be quite complex in the general case.

Fix ddaq display issues

---

Packages/MIES/MIES_Async.ipf

Some users have reported that the debugger pops up when ThreadGroupWait
encounters a problem.
As this is not reproducible on this developers machine, let's just use
the standard solution and disable/reenable debug on error.

ASYNC_Stop: Avoid debugger popping up on ThreadGroupWait errors

---

Packages/MIES/MIES_AmplifierInteraction.ipf

AI_OpenMCCs cleanes up duplicates itself and opens only one MCC per unique
serial number. The amplifier title list is cleaned up accordingly.
closes https://github.com/AllenInstitute/MIES/issues/406

AI_OpenMCCs is now aware of duplicate amplifier serial numbers

---

Packages/doc/developers.rst
tools/installer/installer.nsi

Allow installing for all users with the silent installer

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_Debugging.ipf
Packages/MIES/MIES_TangoInteract.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_TestNWBExportV1.ipf
Packages/doc/Doxyfile
tools/functionprofiling.sh

@timjarsky Is good if CI passes.

Misc fixes

---

Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_Utils.ipf

This is needed for NWBv2 support.

Add RFC4122 style UUIDs

---

Packages/MIES/MIES_DAEphys.ipf

DAP_OpenCommentPanel: Move comment window to the left

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_DataAcquisition_Multi.ipf
Packages/MIES/MIES_DataConfiguratorITC.ipf
Packages/MIES/MIES_Oscilloscope.ipf
Packages/MIES/MIES_TestPulse_Multi.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

Fix power spectrum display

---

Packages/MIES/MIES_Async.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_ThreadsafeUtilities.ipf

fixes https://github.com/AllenInstitute/MIES/issues/483
requires: https://github.com/AllenInstitute/MIES/pull/485
also adapted ASYNC framework to use the threadsafe utility function instead of its own.

Fix for TS_ThreadGroupPutDFR

---

Packages/doc/conf.py
tools/build-documentation.sh
tools/docker/Dockerfile
tools/docker/build-documentation.sh

Update our documentation toolchain to something less ancient

---

Packages/doc/CalculateTPLikePropsFromSweep.rst
Packages/doc/asyncframework.rst
Packages/doc/index.rst

@MichaelHuth At least in sphinx 3.0.0 it works by just adding a sphinx reference.

Documentation: Add references to figure of general interest

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_GuiUtilities.ipf

Close #450.
I've changed the behaviour back that the user must *not* click at the up/down buttons. As this would have the side effect of changing the value.
I've also added two more gems ;)

Allow user to adjust the setvariable limits

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf

From https://twitter.com/timjarsky/status/1083778985111109632 and
private communication with Tim Jarsky.
Close #518.
I've guessed the chirp position.

MIES_AnalysisFunctions_PatchSeq.ipf: Document the order of the execution

---

Packages/MIES/MIES_DAEphys_GuiState.ipf

WaveClear does not seem to be required at this location.
Just some leftover?

Removed WaveClear in DAG_Update

---

Packages/MIES/MIES_DAEphys_Macro.ipf

The old entries were just wrong.

DAephys: Adapt help for Repeated acquisition and repeat sets

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_MiesUtilities.ipf

Close #122.
How about not adding a setting but showing both? This is what I implemented now.

Show headstage in databrowser/sweepbrowser as well

---

Packages/MIES/MIES_TestPulse.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

I just noticed that TP_AnalyzeTP takes a lot of time here. So I went out and did some changes. Totally WIP and not much tested.

Make analyzing TP faster

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_Structures.ipf

That PR is quite embarassing. To leave such an obvious enhancement like effb9eed (PulseAverage: Never do a full update, 2020-07-16) undone for such a long time.

Faster pulse average updates

---

Packages/MIES/MIES_PulseAveraging.ipf
Packages/doc/releasenotes.rst
Packages/doc/releasenotes_template.rst

Release 2.1

---

Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_Utilities.ipf

NWB: Add the IP build version to the generator dataset

---

Packages/MIES/MIES_GuiUtilities.ipf

That assertion message is coming up quite often, so be nice and output
the control name and string value.

SetPopupMenuString: Enhance assertion message

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser_Export.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_TraceUserData.ipf
Packages/MIES/MIES_Utilities.ipf

Various bugfixes for the release 2.1 branch

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_AnalysisBrowser_LabNotebookTPStorageBrowser.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_Downsample.ipf
Packages/MIES/MIES_IgorHooks.ipf
Packages/MIES/MIES_Menu.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_PackageSettings.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf

This needs real live user testing to see if it is useful or just annoying,

Remember window positions

---

Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_GuiUtilities.ipf

Polish PA plot  and databrowser

---

Packages/MIES/MIES_IVSCC.ipf

IVS_ExportAllData: Remove existing NWB files first as requested

---

Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DAEphys_GuiState.ipf
Packages/MIES/MIES_DebugPanel.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_Oscilloscope.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf
Packages/Testing-MIES/UTF_SweepFormula.ipf

Accept - as sign in SweepFormula

---

Packages/MIES/MIES_ProgrammaticGUIControl.ipf
Packages/Testing-MIES/UTF_PGCSetAndActivateControl.ipf

This is required so that the new colortable popup menu for the PA plot works with all our tools.

Add colortable support for PGC_SetAndActivateControl and popup menues

---

Packages/MIES/MIES_DataConfiguratorITC.ipf

This finally allows us to return multiple values with non-hacky
solution.

DC_CalculateChannelColumnNo: Use MRS syntax instead of complex values

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf

One of the bugs found in the presentation.

Fix wave note display sweep browser

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_TestNWBExportV1.ipf
Packages/Testing-MIES/UTF_TestNWBExportV2.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/doc/mies-concepts.rst

@timjarsky Unfortunately really quite minor.
We need to chat about the changes. As now some waves like TPStorage don't exist if they don't have any content. Maybe someone is relying on them being present.

Minor nwb speedups

---

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_IVSCC.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_Labnotebook.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqDaScale.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqFastRheoEstimate.ipf
Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf
Packages/Testing-MIES/UTF_PatchSeqRamp.ipf
Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf
Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Add multipatchseq dashboard support

---

Packages/MIES/MIES_AnalysisFunctions.ipf
Packages/Testing-MIES/UTF_SetControls.ipf

SetControlInEvent: Warn when trying to set a control which can not be set

---

Packages/doc/conf.py
Packages/doc/user.rst
tools/build-documentation.sh
tools/docker/Dockerfile
tools/docker/build-documentation.sh
tools/docker/requirements.txt

Add video to docu

---

Packages/MIES_Include.ipf
Packages/doc/.gitignore
Packages/doc/installation.rst
tools/build-documentation.sh

Close #543
Close #707
@timjarsky What do you think? I got a bit carried away, but it is much easier to use now. You can trigger the too-old version by replacing 35712 with 40000.

Better nightly version update and more docu for users

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqFastRheoEstimate.ipf
Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf
Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf
Packages/Testing-MIES/UTF_TestNWBExportV1.ipf
Packages/Testing-MIES/UTF_TestNWBExportV2.ipf
Packages/Testing-MIES/UTF_WaveBuilder.ipf

Fix and clarify wave types

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/Testing-MIES/UserAnalysisFunctions.ipf

Fix sweep rollback deleting the wrong sweeps

---

Packages/MIES/MIES_PulseAveraging.ipf
Packages/Testing-MIES/UTF_PA_Tests.ipf

With time alignment enabled the pulses get shifted against each other,
such that their x position and the maximum position matches.
When average was applied to these sets the different count of pulses
at the left and right boundaries resulted in artefacts due to the
different statistics.
Now the average wave is restricted to the range where all pulses have data.
This is automatically carried over to the deconvolution data.
close https://github.com/AllenInstitute/MIES/issues/752

PA: With TA the average wave is restricted to common range of all traces

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_ProgrammaticGUIControl.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqDaScale.ipf
Packages/Testing-MIES/UTF_PGCSetAndActivateControl.ipf
Packages/doc/dot/multi-patch-seq-dascale.dot
Packages/doc/dot/multi-patch-seq-fast-rheo-estimate.dot
Packages/doc/dot/multi-patch-seq-spike-control.dot
Packages/doc/dot/patch-seq-dascale.dot

Make MSQ analysis functions work with indexing

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf

DA_Ephys: Add strongly worded message to sweep rollback control

---

Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

Forgotten in 607e61d2 (AutoBias: Make percentage and interval configurable, 2017-09-28).

DC_PlaceDataInDAQDataWave: Add autobias percentage and interval to LBN

---

Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataConfigurator.ipf

Bugfix: Clearing DAQDataWave_TP was faulty

---

README.md

README.md: Clarify supported hardware

---

Packages/MIES/MIES_Cache.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_TestPulse.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf

Various stuff I've encountered while diving into #861.

Various TP issues

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_Main.ipf
Packages/Testing-MIES/UTF_PA_Main.ipf

Remove enable async aquisition checkbox from DAEphys

---

Packages/MIES/MIES_MiesUtilities.ipf

Close #883.
@ru57y34nn This should fix your issue. Please test.
@timjarsky This fix is straight from main.

GetSweepsWithSetting: Don't treat textwaves like numeric waves

---

Packages/MIES/MIES_IVSCC.ipf

Tighten baseline qc criteria and return number of errors in IVS_ConfigureMCC

---

Packages/MIES/MIES_IVSCC.ipf

See #867.
Will merge when CI passes.

[Forwardport] Bugfix/tighten baseline qc criteria

---

Packages/MIES/MIES_BackgroundWatchdog.ipf
Packages/MIES/MIES_CheckInstallation.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_Debugging.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_AnalysisFunctionHelpers.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf

Various minor fixes

---

Packages/Testing-MIES/UTF_AnalysisFunctionHelpers.ipf
Packages/Testing-MIES/UTF_AsynFrameworkTest.ipf
Packages/Testing-MIES/UTF_Configuration.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_HelperFunctions.ipf
Packages/Testing-MIES/UTF_Labnotebook.ipf
Packages/Testing-MIES/UTF_Main.ipf
Packages/Testing-MIES/UTF_PA_Tests.ipf
Packages/Testing-MIES/UTF_TraceUserData.ipf
Packages/Testing-MIES/UTF_UpgradeDataFolderLocation.ipf
Packages/Testing-MIES/UTF_UpgradeWaveLocationAndGetIt.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/Testing-MIES/UTF_WaveBuilder.ipf
Packages/Testing-MIES/UTF_WaveBuilderRegression.ipf

This is now using the new naming convention.

Cleanup some test internals

---

Packages/doc/epoch_information.rst

Packages/doc/epoch_information.rst: Fix list formatting

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

The Igor Pro version is not fine-grained enough.

Labnotebook: Store the Igor Pro build as well

---

Packages/doc/developers.rst
tools/nextFreePRNumber.sh
tools/pre-push

I also wrote some code so that this will be enforced on my end.

Add branch naming scheme documentation and enforce script

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Add sweep reconstruction for borked up sweep rollback

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_ForeignFunctionInterface.ipf
Packages/MIES/MIES_IVSCC.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_IVSCC.ipf

Add publisher subscriber support (forward port)

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_IVSCC.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_OverlaySweeps.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf

Close https://github.com/AllenInstitute/MIES/issues/923
Close #553
Close #602
Requires #579 to be merged.

Sweepbrowser dashboard

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf
Packages/doc/releasenotes.rst
Packages/doc/releasenotes_template.rst
tools/create-changelog.sh
tools/get-changed-controls.sh

Prepare for release 2.2

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf

DC_PlaceDataInDAQDataWave: Document the indexing end set for DA channels

---

.gitmodules
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_GuiState.ipf
Packages/MIES/MIES_Debugging.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HelperFunctions.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Backport of: NWB_CheckForMissingSweeps: Handle no sweeps gracefully #940 

---

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_OverlaySweeps.ipf
Packages/MIES/MIES_Utilities.ipf

Avoid spike control asserting out

---

Packages/MIES/MIES_DAEphys.ipf

DAP_CheckSettings/DAP_CheckHeadStage: Handle mismatched MCC gains nicer

---

Packages/MIES/MIES_Async.ipf
Packages/MIES/MIES_CheckInstallation.ipf
Packages/MIES/MIES_Debugging.ipf
Packages/MIES/MIES_ThreadedFIFOHandling.ipf
Packages/MIES_Include.ipf
Packages/Testing-MIES/UTF_AsynFrameworkTest.ipf
Packages/Testing-MIES/UTF_Labnotebook.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/doc/developers.rst
tools/unit-testing/check_mies_compilation.sh

Allow debugging threadsafe functions

---

Packages/MIES/MIES_AnalysisFunctions.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DANDI.ipf
Packages/MIES/MIES_InputDialog.ipf
Packages/MIES/MIES_Menu.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/MIES_Include.ipf

Implements the download part from #896.

Download from DANDI

---

Packages/MIES/MIES_AmplifierInteraction.ipf
Packages/MIES/MIES_AnalysisFunctions.ipf

Found with latest IP9 which made that a compile error.

Remove duplicated case labels

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_Downsample.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_OptimzedOverlapDistributedAcquisition.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf

Faster code with WaveMinAndMaxWrapper on IP9

---

Packages/MIES/MIES_Menu.ipf
Packages/MIES/MIES_Oscilloscope.ipf
Packages/MIES/MIES_StimsetAPI.ipf
Packages/Testing-MIES/UTF_StimsetAPI.ipf

Make data display for ni faster

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_ForeignFunctionInterface.ipf
Packages/MIES/MIES_PressureControl.ipf

Close #965.
@aleonlein Ready to test.

Publish pressure method changes

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf

Make baseline checking more robust

---

Packages/MIES/MIES_AnalysisFunctions.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf

PSQ_Chirp: Use better resistance value

---

Packages/MIES/MIES_GuiPopupMenuExt.ipf

Fix gui popup menu length

---

Packages/MIES/MIES_AcquisitionStateHandling.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_ForeignFunctionInterface.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_HelperFunctions.ipf
Packages/Testing-MIES/UTF_IVSCC.ipf
Packages/Testing-MIES/UTF_Main.ipf
Packages/Testing-MIES/UTF_Pressure.ipf

Publish seal formation and more pressure entries in TPStorage

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_EnhancedWMRoutines.ipf
Packages/MIES/MIES_Epochs.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_Epochs.ipf

This is a grab-bag of minor bugfixes and enhancments from various PRs. Put here so it can be fast-tracked.

Various things

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf

Add "Set cycle count" LBN entry for TTL channels

---

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf

Fix failure message gathering in the analysis function dashboard

---

Packages/doc/releasenotes.rst
Packages/doc/releasenotes_template.rst

Last commit: e504a25a (Merge pull request #1031 from AllenInstitute/feature/1031-pressure-sealed-message, 2021-09-07)
Not yet included:
- https://github.com/AllenInstitute/MIES/pull/1032
- https://github.com/AllenInstitute/MIES/pull/1037
- https://github.com/AllenInstitute/MIES/pull/1044
Already included:
- https://github.com/AllenInstitute/MIES/pull/1050

Prepare for new release

---

tools/nwb-read-tests/Dockerfile
tools/nwb-read-tests/run.sh

Update testing with pynwb to use latest 2.0.0 version

---

tools/sign-installer.sh

Sign installer in bamboo

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_SweepFormula.ipf
Packages/doc/SweepFormula.rst

Adds support for multiple graphs by using SweepFormula with the word "and" on a separate line.
Also fixed some more SweepFormula issues and revised some code quality.
The jsonId memory leak was not as critical as it appeared only on errorneous formulas.
close https://github.com/AllenInstitute/MIES/issues/300
Close #1079

Allow multiple graphs from SweepFormula

---

Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/Testing-MIES/UTF_Labnotebook.ipf

`labnotebook("TP Amplitude VC" ,channels(ad),sweeps(), TEST_PULSE_MODE)` works now as expected.

GetLastSettingChannel: Make it work with independent headstage data again

---

Packages/MIES/MIES_Utilities.ipf

We don't have a way of checking if the powershell script worked or not.
But we can at least tell the user what she needs to do and what other
possibilities exist.
Requires: https://github.com/AllenInstitute/ITCXOP2/pull/14

TurnOffASLR: Be a bit more chatty

---

Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/Testing-MIES/UTF_SweepFormula.ipf

Minor fixes for sweep formula panel and sweep functions

---

Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_PatchSeqChirp.ipf
Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf
Packages/Testing-MIES/UTF_PatchSeqRamp.ipf
Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf
Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf

I expect some CI fallout, so I'm having this here separately.

DAEphys: Use 35% as default value for the baseline percentage

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_Epochs.ipf
Packages/MIES/MIES_Structures.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_PatchSeqChirp.ipf
Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf
Packages/Testing-MIES/UTF_PatchSeqRamp.ipf
Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf
Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf
Packages/doc/epoch_information.rst

close https://github.com/AllenInstitute/MIES/issues/1040

Store chunk start/end/name as user epochs

---

Packages/MIES/MIES_SweepFormula.ipf

Close https://github.com/AllenInstitute/MIES/issues/1148

Fix DataBrowser SF tab ToFront button not working

---

Packages/doc/developers.rst

developers.rst: Document new bamboo configuration

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_ArtefactRemoval.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_OverlaySweeps.ipf
Packages/MIES/MIES_PulseAveraging.ipf

Fix scrolling in db/sb

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_Labnotebook.ipf

Add utility function GetHeadStageForChannel

---

Packages/MIES/MIES_Configuration.ipf
Packages/MIES/MIES_Utilities.ipf

Bugfix request from yesterday.

CONF_RestoreDAEphys: Assert out on missing or erroenous stimset path

---

Packages/MIES/MIES_AmplifierInteraction.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_ForeignFunctionInterface.ipf
Packages/MIES/MIES_IVSCC.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_TestPulse.ipf
Packages/Testing-MIES/UTF_Main.ipf
Packages/Testing-MIES/UTF_ZeroMQPublishing.ipf

@ru57y34nn @timjarsky @aleonlein This implements the new messages from #1101 which are:
- clamp mode change
- auto bridge balance
- break in
IVS_ExportAllData returns 0 on success and > 0 else on error.
Close #1101.

Enhance interaction with wse

---

Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_IgorHooks.ipf
Packages/MIES/MIES_PressureControl.ipf

@timjarsky Can you try again with that branch? And if you can reproduce the error please upload the logfiles and post the ticket ID here.

Better error detection on device unlocking

---

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf
Packages/Testing-MIES/UTF_AnalysisFunctionManagement.ipf

Check help string analysis functions

---

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqDaScale.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqFastRheoEstimate.ipf
Packages/Testing-MIES/UTF_MultiPatchSeqSpikeControl.ipf
Packages/Testing-MIES/UTF_PatchSeqChirp.ipf
Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf
Packages/Testing-MIES/UTF_PatchSeqRamp.ipf
Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf
Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf

Various Analysis Functions Dashboard fixes

---

Packages/doc/developers.rst

Added more developers docu on how to retrieve associated headstages/channels from the lab notebook and how to write them to the LBN for tests.

Extend developers documentation for headstage vs channel from LBN functions

---

Packages/doc/releasenotes.rst

Done until 4b88fa7f (Merge pull request #1200 from AllenInstitute/feature/1200-mh_extend_developers_docu, 2021-12-16).
Close #996.

Make new release

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_LogbookViewer.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_TraceUserData.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_TraceUserData.ipf

plot bounds and psq lbn keys

---

Packages/MIES/MIES_IVSCC.ipf

Forgotten in 1a64ca17 (PSQ_SealEvaluation: Add it, 2022-02-22).

IVS_RunGigOhmSealQC: Switch to using the analysis function

---

Packages/MIES/MIES_Cache.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Fix TP fetching from cache for NI hardware

---

Packages/MIES/MIES_SweepFormula.ipf
Packages/Testing-MIES/UTF_SweepFormula.ipf
Packages/Testing-MIES/UTF_SweepFormulaHardware.ipf
Packages/doc/SweepFormula.rst

Part of Milestone 1 of https://github.com/AllenInstitute/MIES/issues/362#issuecomment-1117430426

Increase SweepFormula test coverage

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_PulseAveraging.ipf

This is IP9 only and can thus only now be used.
Part of #649.

RemoveImagesFromGraph: Remove and prefer RemoveImage/ALL

---

Packages/MIES/MIES_DataBrowser_Macro.ipf

@timjarsky This should fix the issue with the enourmous size of the logbook panel below the databrowser.

DataBrowser: Regenerate macro with normal window sizes

---

Packages/MIES/MIES_Configuration.ipf

For backward compatibility reasons this setting is optional.
Close #1398.

MIES_Configuration.ipf: Add "LPF primary output"

---

Packages/MIES/MIES_DAEphys.ipf

Output message for MCC bug with instructions

---

Packages/MIES/MIES_DataConfigurator.ipf

DC_GenerateStimsetFingerprint: Drop dataAcqOrTP argument

---

Packages/Testing-MIES/UTF_PGCSetAndActivateControl.ipf

PGC_SetAndActivateControl: Enhance test coverage

---

Packages/Testing-MIES/UTF_BasicHardwareTests.ipf

Tests: Add ScaleZeroWithCycling

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/Testing-MIES/UTF_HelperFunctions.ipf
Packages/Testing-MIES/UTF_VeryBasicHardwareTests.ipf

Fail tests early if possible

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_HelperFunctions.ipf
Packages/Testing-MIES/UTF_PatchSeqAccessResistanceSmoke.ipf
Packages/Testing-MIES/UTF_PatchSeqPipetteInBath.ipf
Packages/Testing-MIES/UTF_PatchSeqSealEvaluation.ipf
Packages/Testing-MIES/UTF_SweepFormulaHardware.ipf

Close #1335.
@MichaelHuth Please review.

Fix incorrect sweeps and channels members in results wave

---

Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_LogbookViewer.ipf
Packages/MIES/MIES_MiesUtilities.ipf

Update textual labnotebook entries

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_Async.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Files that do not contained any devices were ignored by the analysis browser.
Now they are shown in the list view.
close https://github.com/AllenInstitute/MIES/issues/1270

Analysis Browser: Also allow to load stimsets from stimset only files

---

Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_LogbookViewer.ipf
Packages/MIES/MIES_MiesUtilities.ipf

ED_createTextNotes: Create and update empty slice wave

---

Packages/Testing-MIES/UTF_AsynFrameworkTest.ipf
Packages/Testing-MIES/UTF_Configuration.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_HelperFunctions.ipf
Packages/Testing-MIES/UTF_Main.ipf
Packages/Testing-MIES/UTF_PA_Main.ipf
Packages/Testing-MIES/UTF_PGCSetAndActivateControl.ipf
Packages/Testing-MIES/UTF_UpgradeDataFolderLocation.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/Testing-MIES/UTF_WaveBuilderRegression.ipf

Enable bug message checking also for RunAllTests/PA_Tests

---

tools/clean_mies_installation.sh

tools/clean_mies_installation.sh: Remove old MIES installations [backport]

---

Packages/Testing-MIES/UTF_AnalysisFunctionManagement.ipf
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_ReachTargetVoltage.ipf

Tests: Pefer ST_SetStimsetParameter over direct WPT access

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/MIES/MIES_Menu.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/Testing-MIES/UTF_Utils.ipf
Packages/doc/developers.rst
README.md

MIES_DAEphys.ipf: Add USB-6346 as supported NI hardware for DAC

---

tools/initial-repo-config.sh

tools/initial-repo-config.sh: Make it work when called from subdirectories

---

tools/nwb-read-tests/run.sh

tools/nwb-read-tests/run.sh: Use latest pynwb 2.1.0

---

Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_Debugging.ipf
Packages/Testing-MIES/UTF_HardwareTestsWithBUG.ipf
Packages/Testing-MIES/UTF_Utils.ipf

Avoid differing behaviour for BUG/BUG_TS in CI and production

---

Packages/MIES/MIES_AmplifierInteraction.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_Utilities.ipf

In response to #1435 I did some playing around and found some minor things which are fixed here.

Minor fixes for amplifier handling

---

Packages/MIES/MIES_AcquisitionStateHandling.ipf
Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_ProgrammaticGUIControl.ipf
Packages/MIES/MIES_RepeatedAcquisition.ipf
Packages/Testing-MIES/UTF_Dashboard.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UTF_PGCSetAndActivateControl.ipf
Packages/Testing-MIES/UserAnalysisFunctions.ipf

Some stuff I found while investigating #1421.
The newly added tests for the dashboard also required to add ListBox support for PGC.

Dashboard fix, tests, various other minor stuff

---

Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_TestPulse.ipf
Packages/Testing-MIES/UTF_SweepFormula.ipf
Packages/doc/TPAnalysis_algorithm.rst

Testpulse evaluation range

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/MIES/labnotebook_numerical_description.itx
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf

Add test with no amplifier and other related fixes.

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf
Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_RepeatedAcquisition.ipf
Packages/MIES/MIES_Structures.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/MIES/labnotebook_numerical_description.itx
Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Packages/Testing-MIES/UTF_HardwareMain.ipf
Packages/Testing-MIES/UserAnalysisFunctions.ipf

Add some more labnotebook entries

---

tools/check-code.sh

tools/check-code.sh: Add check for missing newline at EOF

---

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf

To test select MIES panels->Create an issue and verify that the version does include something in "submodule status".
Close #1501

CreateMiesVersion: Fix it

---

Packages/MIES/MIES_AnalysisFunctions.ipf
Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_SetControls.ipf
Packages/tests/HardwareBasic/UTF_DAEphys.ipf
Packages/tests/HardwareBasic/UTF_Databrowser.ipf
Packages/tests/HardwareBasic/UTF_HardwareBasic.ipf
Packages/tests/HardwareBasic/UTF_VeryBasicHardwareTests.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

SetControlInEvent: Allow setting multiple notebooks

---

Packages/MIES/MIES_Configuration.ipf
Packages/tests/HardwareBasic/UTF_DAEphys.ipf

close https://github.com/AllenInstitute/MIES/issues/1097

CONF: Add saving and restoring MCC gain values

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_LogbookViewer.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf

PSQ: Allow to use a user databrowser in parallel

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf

Make browser from SF plot retrievable

---

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf
Packages/MIES/MIES_AnalysisFunctionManagement.ipf
Packages/MIES/MIES_AnalysisFunctionPrototypes.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_TestPulse_Single.ipf
tools/check-code.sh

Check that the list of function prefixes is unique

---

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf
Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf

Keep axes ranges for SF plots with constant SF code

---

Packages/MIES/MIES_Utilities.ipf
Packages/tests/Basic/UTF_Utils.ipf

It is possible to give a dimension a DeepCopyWaveRefWave where referenced data is selectively duplicated. Previously the resulting dimension remained at size 1, whereas it should be properly reduced if higher dimensions are all 1 or 0.
The new utility function ReduceWaveDimensionality addresses this problem. DeepCopyWaveRefWave uses this function to properly reduce the dimensionality.
close https://github.com/AllenInstitute/MIES/issues/203

bugfix for DeepCopyWaveRefWave not reducing dimensionality of waves

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_Epochs.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/tests/Basic/UTF_EpochswoHardware.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf
Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf

close https://github.com/AllenInstitute/MIES/issues/1247
close #1155

SF: Adapt tp operation for new fit mode

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_Oscilloscope.ipf
Packages/tests/Basic/UTF_WaveBuilderRegression.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRamp.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRheobase.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqSquarePulse.ipf
Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf

Avoid memory leaks

---

Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

Restore annotation positions

---

Packages/MIES/MIES_DAC-Hardware.ipf

Fix CheckGetDeviceInfoWithInvalid test on ITC CI box

---

Packages/MIES/MIES_DataAcquisition_Multi.ipf
Packages/MIES/MIES_TestPulse.ipf
Packages/MIES/MIES_TestPulse_Multi.ipf
Packages/MIES/MIES_TestPulse_Single.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_SetControls.ipf
Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

This also updates IPNWB to fix the dead link.

Fail hard on ITC hardware errors

---

Packages/doc/developers.rst

Packages/doc/developers.rst: Update CI section

---

Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/tests/Basic/UTF_Utils.ipf

Various small enhancements and fixes

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_Debugging.ipf
Packages/MIES/MIES_JSONWaveNotes.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_JSONWaveNotes.ipf

@MichaelHuth Please have a look how I implemented the two new features.

Small enhancements for SF

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf
Packages/tests/Basic/UTF_Utils.ipf

@MichaelHuth Please have a look.

EPSP prep v6

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataAcquisition_Multi.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_SamplingInterval.ipf
Packages/MIES/MIES_TestPulse_Multi.ipf
tools/check-code.sh

Avoid function call in for loop statement

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/tests/Basic/UTF_WaveBuilder.ipf

That is something Rusty and I found on my last visit in Dec 2022.
The fallout is that it is confusing output for the user, nothing more.
Close #1586.

Handle custom waves on NWB export better in edge case better

---

Packages/MIES/MIES_ProgrammaticGUIControl.ipf

PGC_SetAndActivateControl: Cleanup documentation and enhance it

---

Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf

PSX prep v9

---

Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_IgorHooks.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

Avoid closing/reopening ITC devices during testing

---

.github/pull_request_template.md
Packages/doc/developers.rst

Packages/doc/developers.rst: Update for GH actions

---

Packages/MIES/MIES_Utilities.ipf

- IndexedDir and IndexedFile return an RTE if the directory or folder can not be accessed. The functions also returns an emtpy string in that case. Thus, as soon as such a folder was encountered further traversal was cancelled. A typical folder is $RecycleBin in Windows where that applies.
- Now the functions are used to retrieve all files or folders at a time. Also RTE conditions are ignored.

bugfix: GetAllFilesRecursivelyFromPath use reliable name retrieval

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DAEphys_Macro.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_ProgrammaticGUIControl.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/tests/Basic/UTF_Macros.ipf
Packages/tests/Basic/UTF_PGCSetAndActivateControl.ipf
Packages/tests/Basic/UTF_Utils.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/HardwareBasic/UTF_DAEphys.ipf
Packages/tests/UTF_HelperFunctions.ipf

Don't save and load read-only setvariable controls

---

Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/HardwareBasic/UTF_Epochs.ipf
Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

More builtins for AcquireData_NG

---

.github/workflows/build-pr.yml
.github/workflows/build-release.yml
.github/workflows/test-igor-workflow.yml
Packages/tests/UTF_HelperFunctions.ipf
README.md
tools/autorun-test.sh
tools/ftp-upload/download-files.sh
tools/ftp-upload/upload-files.sh
tools/report-generator/Dockerfile
tools/report-generator/build.sh

Changes:
- Full PR workflow is now called when doing a main/release workflow.
- Instrumentation is done for builds on the main branch and a coverage report is generated with ReportGenerator. Latest reports can be found here: https://byte-physics.de/public-downloads/aistorage/transfer/report/coverage/
- Add report badges to the Readme file
- Improvements to CI logs and results
- Minor tweaks and bug fixes to CI
More links:
- [CI builds with PR pipeline disabled and old Cobertura artifacts](https://github.com/AllenInstitute/MIES/actions/runs/5120979467#summary-13857797615)
TODO:

Github Actions Improvements

---

.github/workflows/build-pr.yml
.pre-commit-config.yaml
tools/ftp-upload/download-files.sh
tools/nwb-read-tests/run.sh
tools/pre-commit/Dockerfile
tools/pre-commit/run.sh

Add pre-commit CI

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_Configuration.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/MIES/MIES_Menu.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf
Packages/tests/Basic/UTF_Utils.ipf
tools/http-upload/upload-json-payload-v1.php

- only run once per day, not in CI
- Uploads Igor Version incl. BUILD number, Hardware Device List, MIES Version
- Added to StartOrNewHook
close https://github.com/AllenInstitute/MIES/issues/197

Ping website

---

Packages/MIES/MIES_Configuration.ipf
Packages/MIES/MIES_Utilities.ipf

close https://github.com/AllenInstitute/MIES/issues/1810

Fix abort on daephys config save

---

Packages/MIES/MIES_GuiUtilities.ipf

close https://github.com/AllenInstitute/MIES/issues/1806

Allow AdaptDependentControls to be used by any panel

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf

Fix splitTLL assertion

---

Packages/MIES/MIES_DAEphys.ipf

 DAP_UpdateChanAmpAssignPanel: Don't use PGC_SetAndActivateControl for control setting

---

.github/workflows/build-pr.yml
.github/workflows/build-release.yml
Packages/MIES/MIES_SweepFormula.ipf
Packages/tests/UTF_DataGenerators.ipf

@MichaelHuth Please have a look at the SF_PreprocessInput commits.

Remove trailing whitespace in SF code

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/MIES/MIES_SweepFormula_PSX.ipf

Better branch naming compared to #1880

Add routines for extracting the stimset epoch

---

Packages/doc/dot/patch-seq-dascale.dot
tools/sign-installer.sh

We do only search the pulse region.
Close #1898

patch-seq-dascale.dot: Adapt x-range for spike search

---

tools/nwb-read-tests/run.sh

tools/nwb-read-tests/run.sh: Raise pynwb version to 2.5.0

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/tests/Basic/UTF_Utils.ipf

Adds a utility function to duplicate a free/local wave while keeping the targets wave reference intact

Preparation PR for sutter hardware support 1

---

Packages/tests/Basic/UTF_Macros.ipf
Packages/tests/UTF_HelperFunctions.ipf

Make Basic.pxp test execution a bit faster

---

Packages/tests/PAPlot/UTF_PA_Tests.ipf
Packages/tests/UTF_HelperFunctions.ipf

Only close databrowser in CI

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Constants.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Sub.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Supra.ipf

PSQ_DA_Scale: Calculate the pulse duration dynamically

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/tests/UTF_HelperFunctions.ipf

This PR covers a few general things discovered in #1667

Sutter hardware preparation PR

---

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf
Packages/MIES/MIES_DataBrowser.ipf

DB: fix DB_GetPlainSweepList return sweeps sorted

---

.github/workflows/test-igor-rebase-exec-workflow.yml
Packages/MIES/MIES_Cache.ipf
Packages/MIES/MIES_CheckInstallation.ipf
Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Packages/MIES/MIES_Utilities.ipf

Make IgorInfo faster

---

Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf
Packages/tests/UTF_TestNWBExportV1.ipf
Packages/tests/UTF_TestNWBExportV2.ipf

The logic in Acquire_NG was changed to work with Sutter hardware.

Sutter preparation: Adaptation of Acquire_NG for sutter hardware

---

Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/HardwareBasic/UTF_Epochs.ipf
Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

AcquireData_NG: Add FFR configuration for fixed frequency acquisition

---

Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf

Check unassociated DA/AD channels better

---

Packages/MIES/MIES_DataConfigurator.ipf

- As singleStimSet is a 2D wave Igor Pro internally already used round() when converting a floating point index access to an integer index, the additional round() is added to not rely on that behavior. Specifically because it is not consistent in Igor Pro as 1D waves floating point indices are converted by trunc(). Thus, this is no functional change, but explicitly sets the way conversion in case of future changes.
- Also added more in code documentation how the data is treated

DC: Add decimation notes and explicit usage of round() for sample picking

---

Packages/tests/HistoricData/UTF_HistoricData.ipf
tools/check-code.sh

Fix and check casing of doxygen commands

---

Packages/MIES/MIES_SweepFormula_PSX.ipf
Packages/tests/Basic/UTF_SweepFormula_PSX.ipf

The old method was not very robust.
Close #1980

PSX_CreateHistogramOfDeconvSweepData: Rework it completely

---

tools/nwb-read-tests/run.sh

tools/nwb-read-tests: Update pynwb

---

Packages/MIES/MIES_AnalysisBrowser_Macro.ipf
Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_DebugPanel_Macro.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_InputDialog_Macro.ipf
Packages/MIES/MIES_WaveBuilderPanel.ipf
Packages/MIES/MIES_WaveBuilder_Macro.ipf
Packages/tests/HardwareBasic/UTF_Dashboard.ipf
Packages/tests/HistoricData/UTF_HistoricDashboard.ipf
tools/check-code.sh

Including multi row selection as that is missing, at least I saw that in yesterdays live session.
Close #2026

Various dashboard enhancements

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/tests/HistoricData/UTF_HistoricDashboard.ipf

Fix wrong index handling in analysis browser

---

Packages/MIES/MIES_DataAcquisition_Multi.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

bugfix: FIFO2WAVE does not work with single point ranges

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_StimsetAPI.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/tests/Basic/UTF_AnalysisBrowserTest.ipf
Packages/tests/Basic/UTF_StimsetAPI.ipf
Packages/tests/Basic/UTF_Utils.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/UTF_DataGenerators.ipf
Packages/tests/UTF_HelperFunctions.ipf

requires #2063
close #2057
close #2067
close #2068
close #2054

Add tests for nwb stimset roundtrip

---

.github/workflows/build-pr.yml
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_Epochs.ipf
Packages/MIES/MIES_OptimzedOverlapDistributedAcquisition.ipf
Packages/MIES/MIES_SweepSaving.ipf
Packages/MIES/MIES_TestPulse.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_EpochswoHardware.ipf
Packages/tests/Basic/UTF_Utils.ipf
Packages/tests/HardwareBasic/UTF_Epochs.ipf
Packages/tests/UTF_DataGenerators.ipf

- Recreate DataConfigurationresult structure from Labnotebook
- Use the recreated structure to recreate epochs sample exact

Recreate DataConfigurationresult Structure from Labnotebook

---

Packages/MIES/MIES_Async.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf
Packages/tests/Basic/UTF_Utils.ipf
Packages/tests/HistoricData/UTF_AttemptNWB2ExportOnOldData.ipf
Packages/tests/HistoricData/UTF_HistoricData.ipf
Packages/tests/UTF_HelperFunctions.ipf

I had t o patch some more locations in NWB to make it work with ancient LNB and current sweep format.
close #2040
close #2047

Fix nwb export of old MIES data < version 0.7

---

.gitattributes

IPT adds tabs for automatic intendations

Settings: Allow intendations with tabs as automatically done by IPT format

---

.github/workflows/build-pr.yml
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_Downsample.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_Structures.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/MIES/labnotebook_numerical_description.itx
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
Packages/tests/HardwareBasic/UTF_Epochs.ipf
Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
Packages/tests/UTF_TestNWBExportV1.ipf
Packages/tests/UTF_TestNWBExportV2.ipf

part from #1667
requires #2072
close #1938
close #2080

Add channel dependent samplinginterval

---

Packages/MIES/MIES_WaveBuilder.ipf

MIES_WaveBuilder.ipf: Avoid magic numbers for the epoch type

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Epochs.ipf
Packages/tests/UTF_HelperFunctions.ipf

Add U_TP_ epochs for PB and AR, Add U_RA_DS, U_RA_UD in epoch recreation

---

.gitattributes

Make installer smaller

---

Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf
Packages/tests/Basic/UTF_Utils.ipf

- complete recursive evaluation of array elements including of variables / operations
- fix back progression of array creation information in recursive parser
- data type promotion in simple operations

SF: Parser/Executor improvements

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf
Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Configuration.ipf
Packages/MIES/MIES_LogbookViewer.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/MIES/MIES_PulseAveraging.ipf
Packages/MIES/MIES_StimsetAPI.ipf
Packages/MIES/MIES_SweepFormula_PSX.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_SweepFormula_PSX.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_ReachTargetVoltage.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf

Use more IP9 features

---

Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Packages/tests/HistoricData/UTF_HistoricData.ipf
Packages/tests/HistoricData/UTF_HistoricSweepBrowser.ipf

Fix Sweepbrowser display issue with TTL data but no TTL epoch info

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_DataBrowser.ipf
Packages/tests/HardwareBasic/UTF_Databrowser.ipf

Use desired titles for sweepbrowser/databrowser

---

Packages/MIES/MIES_AnalysisBrowser.ipf
Packages/MIES/MIES_Cache.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_MiesUtilities.ipf
Packages/MIES/MIES_TraceUserData.ipf
Packages/MIES/MIES_Utilities.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_Labnotebook.ipf
Packages/tests/Basic/UTF_TraceUserData.ipf
Packages/tests/Basic/UTF_Utils.ipf

This PR bundles some fixes / utils that came up as part of the new SF select PR.

Preparation for new sf select operation

---

tools/nwb-read-tests/run.sh

tools/nwb-read-tests: Update pynwb to 2.8.1

---

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf
Packages/MIES/MIES_AnalysisFunctions.ipf
Packages/MIES/MIES_DAEphys.ipf
Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf

Unify and enhance analysis parameter checking

---

Packages/tests/Basic/UTF_Basic.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions.ipf
Packages/tests/HardwareBasic/UTF_HardwareBasic.ipf
Packages/tests/HistoricData/UTF_HistoricData.ipf
Packages/tests/PAPlot/UTF_PAPlot.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

Igortest will be updated with some performance fixes, wheee...

Update IgorTest and required adaptations

---

Packages/MIES/MIES_SweepFormula_PSX.ipf
Packages/MIES/MIES_Utilities_File.ipf
Packages/MIES/MIES_Utilities_System.ipf
Packages/tests/Basic/UTF_AsynFrameworkTest.ipf
Packages/tests/Basic/UTF_SweepFormula_PSX.ipf

Fix various issues

---

Packages/MIES/MIES_Utilities_Algorithm.ipf
Packages/tests/Basic/UTF_Utils_Algorithm.ipf

GetRowIndex: Enhance it

---

Packages/MIES/MIES_Configuration.ipf
Packages/MIES/MIES_Utilities_File.ipf
Packages/tests/Basic/UTF_Utils_File.ipf

Nicify status messages on configuration output

---

Packages/tests/HistoricData/UTF_HistoricData.ipf

Historic Data tests/DownloadFile: Fail hard on download error

---

README.md

Reformat main readme file

---

Packages/MIES/MIES_DAEphys.ipf
Packages/MIES/MIES_Utilities_Checks.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/tests/Basic/UTF_Utils_Checks.ipf
Packages/tests/Basic/UTF_WaveBuilderRegression.ipf

Don't allow non-finite values in stimsets

---

Packages/MIES/MIES_AmplifierInteraction.ipf
Packages/MIES/MIES_ForeignFunctionInterface.ipf
Packages/MIES/MIES_MiesUtilities_Checks.ipf
Packages/MIES/MIES_MiesUtilities_Config.ipf
Packages/MIES/MIES_MiesUtilities_Logbook.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/tests/Basic/UTF_Utils_Checks.ipf
Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf

FFI_SetCellElectrodeName: Add it

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf

GetOverrideResults: Prefer it and fix the code for ipt

---

Packages/MIES/MIES_PulseAveraging.ipf
Packages/tests/PAPlot/UTF_PA_Tests.ipf

Fix remaining PAPlot tests

---

Packages/MIES_Include.ipf

For the casual MIES administrator the instructions have a bit too much
Igor Pro lingo, so let's try to make it easier to understand.

MIES_Include.ipf: Clarify update instructions

---

tools/report-generator/Dockerfile

This version also requires a newer .NET version.
This now rounds the crap score, see https://github.com/danielpalme/ReportGenerator/issues/699.

tools/report-generator/Dockerfile: Update it

---

Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf
Packages/MIES/MIES_Browser_Plotter.ipf
Packages/MIES/MIES_Configuration.ipf
Packages/MIES/MIES_DAC-Hardware.ipf
Packages/MIES/MIES_Epochs.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_JSONWaveNotes.ipf
Packages/MIES/MIES_MiesUtilities_Recreation.ipf
Packages/MIES/MIES_MiesUtilities_Sweep.ipf
Packages/MIES/MIES_PressureControl.ipf
Packages/MIES/MIES_SweepFormula_PSX.ipf
Packages/MIES/MIES_Utilities_Conversions.ipf
Packages/MIES/MIES_Utilities_GUI.ipf
Packages/MIES/MIES_Utilities_List.ipf
Packages/MIES/MIES_WaveBuilder.ipf
Packages/tests/Basic/UTF_Utils_List.ipf

Various preparations for adaptive enhancements

---

.github/workflows/build-pr.yml

Investigate branch protection bug

---

tools/documentation/Dockerfile
tools/nwb-read-tests/Dockerfile
tools/pre-commit/Dockerfile

tools: Always pass --no-deps for pip install

---

Packages/MIES/MIES_Utilities_Algorithm.ipf
Packages/tests/Basic/UTF_Utils_Algorithm.ipf

This allows to choose /TXOP for textwaves.

GetRowIndex: Add textOp optional parameter

---

Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/MIES_Include.ipf

Various compatibility updates

---

Packages/MIES/MIES_Browser_Plotter.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_Labnotebook.ipf
Packages/tests/HistoricData/UTF_HistoricAnalysisBrowser.ipf

Fix displaying MIES data from 2015

---

Packages/MIES/MIES_StimsetAPI.ipf

ST_SetStimsetParameter: Mention specialities for MID_SWEEP_EVENT

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_DataConfigurator.ipf
Packages/MIES/MIES_ExperimentDocumentation.ipf
Packages/MIES/MIES_MiesUtilities_Logbook.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/MIES/labnotebook_numerical_description.itx
Packages/tests/Basic/UTF_Labnotebook.ipf
Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf

As this setting makes sense for both DAQ (TP during ITI) and TP we also
write it for both.
Close #2024

DA_Ephys: Add power spectrum to labnotebook

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_IgorHooks.ipf
Packages/MIES/MIES_MiesUtilities_Uploads.ipf
Packages/MIES/MIES_Utilities_System.ipf
Packages/MIES/MIES_WaveDataFolderGetters.ipf
Packages/tests/Basic/UTF_Utils_System.ipf
Packages/tests/UTF_HelperFunctions.ipf

Make URLRequest fail gracefully

---

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/tests/Basic/UTF_GuiUtilities.ipf

Bring currently acquiring SCI in dashboard into view

---

tools/nwb-read-tests/nwbv2-read-test.py
tools/nwb-read-tests/requirements.in
tools/nwb-read-tests/requirements.txt

tools/nwb-read-tests: Update pynwb and dandi-cli

---

Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/tests/Basic/UTF_SweepFormula_Operations.ipf

Fix line style for SF operations working on sweep data

---

Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_SweepFormula.ipf
Packages/MIES/MIES_SweepFormula_Helpers.ipf
Packages/MIES/MIES_SweepFormula_PSX.ipf
Packages/MIES/MIES_Utilities_WaveHandling.ipf
Packages/tests/Basic/UTF_SweepFormula.ipf

close https://github.com/AllenInstitute/MIES/issues/2377
close #2372

Bugfix/2380 Make operations copy variable data if they operate on input data

---

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
Packages/MIES/MIES_Utilities_Algorithm.ipf
Packages/MIES/MIES_Utilities_Checks.ipf
Packages/MIES/MIES_Utilities_Conversions.ipf
Packages/MIES/MIES_Utilities_WaveHandling.ipf
Packages/tests/Basic/UTF_Basic.ipf
Packages/tests/Basic/UTF_Utils_Algorithm.ipf
Packages/tests/Basic/UTF_Utils_Checks.ipf
Packages/tests/Basic/UTF_Utils_WaveHandling.ipf
Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions.ipf
Packages/tests/HardwareBasic/UTF_HardwareBasic.ipf
Packages/tests/HistoricData/UTF_HistoricData.ipf
Packages/tests/PAPlot/UTF_PAPlot.ipf

Adaptive prep

---

Packages/MIES/analysis_function_parameters.itx
Packages/tests/Basic/UTF_AnalysisFunctionParameters.ipf
Packages/tests/Basic/UTF_Configuration.ipf
Packages/tests/UTF_HelperFunctions.ipf

Fix CI and update analysis function table 

---

Packages/doc/releasenotes.rst
Packages/doc/releasenotes_template.rst

Commit: f1b6d338c (Merge pull request #2411 from AllenInstitute/bugfix/2411-igor-pro-10-fixes-essentials, 2025-04-29)
Close #2321

Prepare release 2.9

---

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf
Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/tests/HistoricData/UTF_HistoricDashboard.ipf
Packages/tests/UTF_HelperFunctions.ipf

Will merge once CI passes and #2417 is merged.

[Backport] Fix dashboard with edge case data from multiple experiments

---

Packages/MIES/MIES_TraceUserData.ipf
Packages/tests/Basic/UTF_AnalysisFunctionParameters.ipf
Packages/tests/Basic/UTF_AsynFrameworkTest.ipf
Packages/tests/Basic/UTF_DAEphyswoHardware.ipf
Packages/tests/Basic/UTF_JSONWaveNotes.ipf
Packages/tests/Basic/UTF_PGCSetAndActivateControl.ipf
Packages/tests/Basic/UTF_TraceUserData.ipf
Packages/tests/Basic/UTF_UpgradeWaveLocationAndGetIt.ipf
Packages/tests/Basic/UTF_Utils_Algorithm.ipf
Packages/tests/Basic/UTF_Utils_Conversions.ipf
Packages/tests/Basic/UTF_Utils_Mies_Algorithm.ipf
Packages/tests/Basic/UTF_Utils_Mies_Sweep.ipf
Packages/tests/Basic/UTF_Utils_ProgramFlow.ipf
Packages/tests/Basic/UTF_Utils_Strings.ipf
Packages/tests/Basic/UTF_Utils_WaveHandling.ipf
Packages/tests/Basic/UTF_WaveBuilder.ipf
Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf
Packages/tests/UTF_HardwareHelperFunctions.ipf

UTF_AnalysisFunctionParameters.ipf: Remove unneeded AbortOnRTE

---

tools/report-generator/Dockerfile

This should fix https://github.com/danielpalme/ReportGenerator/issues/741.

tools/report-generator: Update

---

Packages/tests/UTF_HelperFunctions.ipf

Packages/igortest: Update it

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/MIES/MIES_Browser_Plotter.ipf
Packages/MIES/MIES_GuiUtilities.ipf
Packages/MIES/MIES_MiesUtilities_GUI.ipf
Packages/tests/HistoricData/UTF_HistoricDataHelpers.ipf
Packages/tests/HistoricData/UTF_HistoricSweepBrowser.ipf

Various databrowser fixes: Overlay channels and non-splitted TTL

---

Packages/MIES/MIES_Configuration.ipf

Force setting disabled checkboxes during control configuration

---

Packages/MIES/MIES_DAEphys.ipf

Only send out pub message about clamp mode change once done

---

Packages/MIES/MIES_Cache.ipf
Packages/MIES/MIES_Constants.ipf
Packages/MIES/MIES_MiesUtilities_System.ipf
Packages/MIES/MIES_ThreadsafeDataSharing.ipf
Packages/tests/Basic/UTF_ThreadsafeDataSharing.ipf
Packages/tests/Basic/UTF_Utils_System.ipf

Preserve cache across new experiment 

---

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Packages/tests/HardwareBasic/UTF_Databrowser.ipf

Databrowser/SweepBrowser: Avoid assertions with no data or unlocked device

---

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Packages/MIES/MIES_DataBrowser_Macro.ipf
Packages/MIES/MIES_OverlaySweeps.ipf

We don't require double clicks.
Close #2517

Databrowser: Check Passed/Failed in Dashboard tab by default

---

Packages/MIES/MIES_Configuration.ipf

CONF_RestoreHeadstageAssociation: Drop MCC sync not being checked warning
