AllenInstitute/MIES

Packages/MIES/MIES_DataConfiguratorITC.ipf
At two locations on filling the DA wave the auto indexing with q was used while
the index was set constant at the target wave.
This did not break the algorithm, but could lead to confusion later.
It was replaced by the well defined index i.
=> FIX: DC_PlaceDataInHardwareDataWave auto indexing by q was used with fixed index

tools/build-documentation.sh, tools/create-release.sh, tools/publish-docs-on-github.sh, tools/upload-github-release-asset.sh
Since the move to github we are using the latest tag for publishing the
master releases.
This tag interfered with our naming scheme for the release packages.
Using the --match option of git describe limits the search to our
expected tags.
=> tools: Handle additional tags properly

tools/upload-github-release-asset.sh
In 3521a47b (tools: Handle additional tags properly, 2019-06-07) we
wanted to force push the tag to origin.
But as it turns out origin is a local repository in bamboo for security
reasons. So we have to use our local copy here as well.
=> tools/upload-github-relase-asset.sh: Fix latest tag pushing again

Packages/MIES/MIES_OptimzedOverlapDistributedAcquisition.ipf
There is no reason why we only want integers.
Broken since d102c07d (Add new data acquisition mode: Optimized overlap
distributed acquisition, 2016-08-10).
The oodDAQ regression test data was also regenerated.
Bug pointed out by Michael Huth.
=> Bugfix: Use floating point conversion %g for building the region list

Packages/Testing-MIES/UTF_Utils.ipf
We can not be sure that the numbers from GetReproducibleRandom() do not
repeat.
This test is already failing occasionally in IP7 as well.
Close #209.
=> Tests: Remove RandomTest

Packages/MIES/MIES_IgorHooks.ipf
With IP8 AfterCompileHook with the start of the ASYNC framework modified always the
experiment. This prevents running Igor automatically with
Igor64.exe /I "experiment.pxp" as Igor asks for save of changes after startup
and compilation before loading experiment.pxp.
This change lets Igor ignore the ExperimentModified condition through the
Async FW start. Igor does not save the threadstate anyway on experiment save.
=> fix that the experiment was always modified, even when newly created

Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
The num2str standard function uses a precision of 5 digits by default.
In some cases this is not sufficient. num2strHighPrec solves this by adding an
optional precision parameter to be able to use a defined number of digits.
- also added tests to UTF_Utils.ipf for num2strHighPrec.
=> Utility function num2strHighPrec to extend num2str with defined precision

Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
This utility function converts a list with different separators to a multi dimensional text wave using row major order. As the list length can be dynamic the text wave will be filled sparse from the top. Remaining text wave elements contain empty strings.
- added tests for ListToTextWaveMD to UTF_Utils.ipf
=> Add utility function ListToTextWaveMD

Packages/MIES/MIES_DAEphys.ipf
There still existed a few situations where it happens that existing
GUIState waves are not in sync with the available controls of the
DA_Ephys panel. e.g. if a dev has changed controls without increasing
the PANEL VERSION constant. Or if an experiment was loaded with an open
panel with a different control state.
The fix is to reset the GUIState waves if
- The panel is recreated after an experiment load with the name
BASE_WINDOW_TITLE. The reset is done in AfterFileOpenHook.
- The panel is locked as this changes the panel title and thus the
the path to the GUIState waves
- The panel is unlocked as this changes the panel title and thus the
the path to the GUIState waves
- The panel is created
=> fix for cases where DA_Ephys panel is not in sync with GUIState waves

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf
In 3a4da735 (DA_Ephys: Generalize controls for setting multiple channel
values, 2016-05-11) we added the all checkboxes for the AD/DA/TTL tabs.
But the TTL checkbox was assigned the wrong tab control procedure
therefore it never showed up.
Fix that and regenerate the panel.
Close #227.
=> DA_Ephys: Show TTL all checkbox properly

Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Bug introduced in d25b9d57 (Refactor GetTTLStimSets to be hardware
independent, 2019-06-28).
=> NWB_GetStimsetFromSweepGeneric: Don't fail without TTL stimsets

Packages/MIES/MIES_DataConfiguratorITC.ipf
Since 0f5cac24 (P_PressureMethodPossible: Handle TP during DAQ as well,
2019-02-18) we use DC_GetChannelTypefromHS to figure out if we can use
the pressure methods or not.
But we call this function also for the currently selected headstage for
pressure control and this might just be not active.
AFH_GetDACFromHeadstage returns NaN for inactive headstages so we need
to handle that before AFH_GetITCDataColumn correctly complains.
=> DC_GetChannelTypefromHS: Handle inactive headstages properly

Packages/MIES/MIES_MiesUtilities.ipf
With headstage removal we can have sweeps where we don't have data
in the reference/diagonal elements. Currently we bug out in this case.
But let's just not align these.
Close #206.
This fix now results in some pulses not being aligned as the reference traces for the alignment are not available. We can have a chat if this is not what you expect.
=> TimeAlignmentIfReq: Handle missing reference position

Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_MiesUtilities.ipf
Bug introduced in f256dc50 (Move background tasks initialization into
common routine, 2019-04-10).
Close #248.
=> SetupBackgroundTasks: Don't start the timer task for single device DAQ

Packages/MIES/MIES_Oscilloscope.ipf
We don't use any dimension offsets and delta for the columns/y
dimension.
Bug introduced in fac268c1 (Acquisition support for NI DAC devices in
multi device mode, 2018-08-03).
=> SCOPE_NI_UpdateOscilloscope: Remove useless y scale setting

Packages/MIES/MIES_Cache.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DataAcquisition_Multi.ipf, Packages/MIES/MIES_DataConfiguratorITC.ipf, Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_Oscilloscope.ipf, Packages/MIES/MIES_SamplingInterval.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/MIES/MIES_TestPulse_Multi.ipf
We do call TP_GetTestPulseLengthInPoints for every oscilloscope update when "TP during DAQ channels" are on.
=> Speedup some functions which are called often during DAQ/TP

Packages/MIES/MIES_Oscilloscope.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
This PR adds the fix for the problem that only the last TP channel was stored.
Add Tests for TPDuringDAQ on multiple channels and check for TPs in stored data.
closes https://github.com/AllenInstitute/MIES/issues/255
=> Fix for Stored TPs + Tests

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
Ever since 916f26e4 (TPStorage: Keep all data in one wave, 2018-10-17)
the check that the TPStorage index is larger than the request number of
cycles is wrong as we don't create a new TPStorage wave on every TP start.
Let's introduce a new index to the TPStorage wave note which tracks the
NOTE_INDEX when starting TP. We can then use the difference between the
two to judge if we are done or not.
Close #263.
=> TP_CheckIfTestpulseIsRunning: Fix it by using the correct index

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_WaveBuilderPanel.ipf
Since forever we only restored the cursors A and B.
For a future application we want to use all cursors, so it is quite
inconvenient that only A and B are restored.
Introduce GetCursorInfos/RestoreCursors and remove RestoreCursor to
handle that.
Close #277.
=> Restore always all cursors

Packages/Testing-MIES/UTF_AnalysisFunctionManagement.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_Epochs.ipf, Packages/Testing-MIES/UTF_MultiPatchSeqDaScale.ipf, Packages/Testing-MIES/UTF_MultiPatchSeqFastRheoEstimate.ipf, Packages/Testing-MIES/UTF_PatchSeqDAScale.ipf, Packages/Testing-MIES/UTF_PatchSeqRamp.ipf, Packages/Testing-MIES/UTF_PatchSeqRheobase.ipf, Packages/Testing-MIES/UTF_PatchSeqSquarePulse.ipf
A common error when executing the tests is that the MCC application is
not open.
We already check that we got a two amplifiers, but only with a CHECK_*
and that made us continue.
Use a REQUIRE_* and fail immediately.
=> Hardware Tests: Fail hard without MCC app open

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf, Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_Menu.ipf, Packages/MIES_Include.ipf
DataBrowser panel macro joined in single recreation macro
This allows to use the recreation workflow as with the DAEphys panel
Added Menu entry "Reset and store current DataBrowser panel", it works
the same way as the already present DAEphys panel recreation.
The SweepBrowser panel that used partially the same window creation macros
uses now fully the DataBrowser macro as well.
Further changes:
- Open functions for SweepBrowser and DataBrowser use both DataBrowser macro
- Init routines for DataBrowser SubWindows only setup dynamic properties.
The SubWindow creation macros have been removed.
- The DataBrowser window creation macro was moved to an own ipf file:
MIES_DataBrowser_Macro.ipf
- new: DB_ResetAndStoreCurrentDBPanel() utility function for generating
DataBrowser recreation.
- All …
=> Enable resizable DataBrowser BrowserSettings subwindow

Packages/MIES/MIES_PressureControl.ipf
In 66fca8ab (DAEphys: Rework device selection logic, 2019-10-08) we
replaced all calls of HW_ITC_ListDevices with a call to
DAP_GetITCDeviceList. And in this case here we wanted to be extra smart
and just use DAP_GetDACDeviceList.
But for the updating the list of pressure devices we don't need the list
of devices capable of DAQ but all unlocked devices.
=> DAEphys: Fix pressure device listing

Packages/MIES/ACL_UserdataEditor.ipf
Added two popup menus that offer all available userdata keys to
be selected independently on each column.
- Currently column sorting resets the popup menu to the first entry.
- The key selection now also has an entry '- empty -' to select the global userdata key.
- When choosing a control type, the key list is reduced accordingly except when choosing SubWindow only (*).
(*) This has to be resolved differently by allowing the Panel selection to select SubWindows as well from the list.
=> ACL UserData Editor modification with two column key selection

Packages/MIES/MIES_AnalysisFunctionManagement.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DataConfiguratorITC.ipf, Packages/MIES/MIES_Indexing.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_TestNWBExportV1.ipf
=> Allow tp during daq with indexing

Packages/MIES/MIES_DataConfiguratorITC.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
Since 39c58802 (DC_MakeOscilloscopeWave: Rewrite, rename and call
directly from DC_ConfigureDataForITC, 2019-09-02) we had better defaults
for the channel data. As it turned out it is too confusing to have
different defaults for different channel types.
So let's just use NaN for all of them.
Close #316.
=> DC_InitDataHoldingWave: Initialize all channels to NaN

Packages/MIES/MIES_Constants.ipf
Until now we only try four times to get an open port. But some users have
a lot of different Igor instances open, so in order to not annoy them we
now try harder.
=> 🎃 StartZeroMQMessageHandler: Use more trials for finding an unused port

Packages/MIES/MIES_DAEphys_GuiState.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_HardwareMain.ipf
This test checks if ASYNC_ReadOut treats remaining data properly even if the panel was closed.
Currently the tests fails if there is still data in the readout queue after the DAEphys panel was closed. So the fail is timing dependent and does not happen always.
=> Add test for correct readout of TP data after DAEphys panel was closed

Packages/MIES/MIES_DataAcquisition.ipf
DQ_ApplyAutoBias referred to non existing panel
When the DA_Ephys panel is killed while TP is running or TP is stopped then
on next TP start the remaining data is read out from Async.
This means the panel can already have been closed or reopened.
The fix skips the Auto Bias apply if the window is not present any more.
However, if in regular operation a user opens a new DA_Ephys panel and locks
it to the same device, DQ_ApplyAutoBias will work with the current GUI state
when referring to the old TP data.
closes https://github.com/AllenInstitute/MIES/issues/361
=> fix for AbortTP test failing

Packages/MIES/MIES_SweepFormula.ipf
Do not use the `KillOrMoveToTrash` functionality for evaluated sweep
formula waves.
Closes #351
=> Preserve SweepFormula wave location

Packages/MIES/MIES_PressureControl.ipf
Followup fix from b6b031ab (fix for AbortTP test failing,
DQ_ApplyAutoBias referred to non existing panel, 2019-11-08).
This situation can happen if we called from TP_ROAnalysis which is the
readout function from the async framework.
=> P_PressureControl: Do nothing if the panel is not locked

Packages/MIES/MIES_DataConfiguratorITC.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_TestNWBExportV1.ipf, Packages/doc/labnotebook-docs.rst
Unassociated DA/AD labnotebook entries are suffixed with
"UNASSOC_$channelNumber". At first sight this might indicate that the
entries are not distinct if you have multiple unassociated DA/AD
channels with the same channel number.
But it turns out that we don't have labnotebook entries which have the
same name for the DA and AD channels.
In order that it also stays like that we add a small test to check that.
=> Document specialities about unassociated entries from more

Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_TestNWBExportV1.ipf
Close #375.
I've made the possibility of exporting a NWB file without history much smaller.
We could also remove the `writeIgorHistory` parameter from `NWB_ExportAllData` alltogether and always store the experiment history. I would be in favour of that.
=> Enhance history storing in nwb

Packages/MIES_Include.ipf
This fixes a bug which can be more-or-less easily triggered when the
databrowser/sweepbrowser is open, a formula plot is open and the databrowser/sweepbrowser
is closed.
It does not immediately crash but might also hang on for a while.
The reason is that the following code
Function crash()
NewDataFolder/O/S foo
make ddd
display ddd
SetDataFolder root:
killwrapper("root:foo")
End
ThreadSafe Function killwrapper(String dfPath)
KillDataFolder/Z $dfPath
End
kills the ddd wave for old IP versions. But that wave is displayed and
thus must not be killed.
=> Require latest IP8 nightly version

Packages/MIES_Include.ipf
This fixes a bug for IP 32bit where
make wv = {1}
MatrixOP/P=1 out = sumCols((-1) * wv)^t
gave 0 instead of -1.
And that is used in the sweep formula code itself and was uncovered by
one of the tests.
Close #390.
=> Require latest IP8 nightly

Packages/MIES/MIES_AmplifierInteraction.ipf, Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_DataConfiguratorITC.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_Menu.ipf, Packages/MIES/MIES_ProgrammaticGUIControl.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/MIES_Include.ipf, Packages/Settings/1_DA_Ephys.json, Packages/Settings/2_DataBrowser.json, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_Configuration.ipf, Packages/Testing-MIES/UTF_Main.ipf, tools/unit-testing/ConfigurationTest.txt, tools/unit-testing/ConfigurationTest_DupCheck1.txt, tools/unit-testing/ConfigurationTest_DupCheck2.txt, tools/unit-testing/ConfigurationTest_Relevant.txt, tools/unit-testing/DA_Ephys.json
- New file MIES_Configuration.ipf with functions to serialize the state of a
GUI window to a file with generic function CONF_SaveWindow/CONF_RestoreWindow
- Specialized function for DA_Ephys panel save/restore that additionally stores
the configuration information of the old ExpConfig approach.
CONF_SaveDAEphys/CONF_RestoreDAEphys
- public functions to save a control, window or window with all its subwindows
to json
- Restore of controls is configurable by setting userdata properties
- human readable nice names for each control
- flag to ignore control on save
- flag to ignore control on restore
- priority value that allows to define the order of control restore
- flag for buttons if they should be activated on restore
- flag that buttons get only saved if they should be activated on …
=> Generic GUI Load/Save and DA_Ephys Experiment Config Load/Save using customized generic way

Packages/MIES/MIES_SweepFormula.ipf, Packages/Testing-MIES/UTF_SweepFormula.ipf
Request by Tim Jarsky.
CLose #394.
=> SweepFormula: Always return 0 for instantaneous with too few levels

tools/build-documentation.sh
Incompatible versions result in difficult to understand error messages.
=> tools/build-documentation.sh: Check sphinx-build version

Packages/MIES/MIES_Utilities.ipf
The second open is not needed and leaves the file still locked on
windows as there is no corresponding close.
Bug introduced in 1f9f39c2 (Added utility function used in
MIES_Configuration, 2019-12-12).
=> LoadTextFile: Avoid opening the file twice

Packages/MIES/MIES_BackgroundWatchdog.ipf, Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Settings/1_DA_Ephys.json, Packages/Settings/1_DA_Ephys_rig.json
The AutoLoader (Load Standard Configuration) is now aware of [Name]_rig.json files that complement [Name].json files with a panel configuration. 
The rig file support is reduced to work for for DA_Ephys panels only.
Changed StimSet path behavior for DA_Ephys configuration laoding:
- when path is "" then StimSet loading is skipped
- when path is set and file does not exist a message is shown
- when path is set and file exists it is loaded without dialog.
I added an adapted configuration using a rig file.
Due to the StimsetPath change it is required to either preLoad the default stimsets or adapt the stimset path to the local location of the default nwb file in 1_DA_Ephys.json. If not adapted the panel restoration will fail when it tries to set a Stimset that was not previously loaded. …
=> Loading split configuration files

Packages/MIES/MIES_AmplifierInteraction.ipf
- originally intended was that AI_GetMCCSerialNumbers returns a wave
with amplifier serial numbers without duplicates, but it did not.
The function now correctly returns the wave without duplicates .
DeleteDuplicates returns the cleaned up wave as return wave.
=> AI_GetMCCSerialNumbers returns now a wave without duplicates as intended

Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Utilities.ipf
Now the source (rig) file name as well as the conflicting paths in the config
files are printed if a conflict is encountered.
- The previous ASSERTion was replaced with a simple Abort.
closes https://github.com/AllenInstitute/MIES/issues/414
from https://github.com/AllenInstitute/MIES/pull/397#issuecomment-571992950
and https://github.com/AllenInstitute/MIES/pull/397#issuecomment-572169844
=> More specific error message for conflicts in split configurations

Packages/MIES/MIES_AmplifierInteraction.ipf, Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf, Packages/MIES/MIES_ExperimentConfig.ipf, Packages/Settings_template/1_DA_Ephys_rig.json
In the configuration for headstages a new field "Amplifier Channel"
was added (constant EXPCONFIG_JSON_AMPCHANNEL) that sets the amplifier channel.
Currently typical values for amplifier channel are 1, 2 or null.
See also updates default 1_DA_Ephys_rig.json file.
closes https://github.com/AllenInstitute/MIES/issues/400
Close #416.
=> Add configuration field Amplifier Channel to specify channel explicitly

Packages/MIES/MIES_Oscilloscope.ipf
This is the suggested method but also does not have any functional
change.
=> RES_FORMAT_STR: Always use two backslashes for IP escape sequences

Packages/MIES/MIES_MiesUtilities.ipf
sprintf is still limited to some maximum length of the string inserted via
%s.
=> AddTraceToLBGraph: Avoid too long string error

Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
The `ParseISO8601TimeStamp` is tested with static strings (taken from a
wikipedia page) and generated strings that come from the
`GetIso8601TimeStamp` function.
=> ParseISO8601TimeStamp: Add support for parsing local time zone offsets

Packages/Testing-MIES/UTF_Configuration.ipf
In 38b90aba (Configuration: Introduce subgroups and add more amplifier
settings, 2020-01-30) some changes to the JSON configuration code was
added. This also changed the EOLS in the reference JSON files for testing.
And since then these tests are failing.
By normalizing the JSON documents, via parse and dump, the tests now
pass again.
=> Tests: Fix failing json configuration tests

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Since TP during DAQ was added in fce6612d
(DC_PlaceDataInHardwareDataWave support for TPwhileDAQ on DAC channels,
2019-01-04) we bug out in the dashboard when we have that kind of data.
The reason is that we don't have a Stimset Cycle ID for TP during DAQ
channels.
=> AD_FillWaves: Ignore TP during DAQ channels

Packages/MIES_Include.ipf
A potential crash in the threading code was fixed in response to a bug
report of ours.
=> Require latest nightly build

Packages/MIES/MIES_Utilities.ipf
We don't have to request a new random seed on every call. This also
might result in duplicated UUIDs if GenerateRFC4122UUID() is called too
quickly.
Bug introduced in a06633d4 (Add RFC4122 style UUIDs, 2020-02-26).
=> GenerateRFC4122UUID: Don't call NewRandomSeed

Packages/MIES/MIES_BackgroundWatchdog.ipf
In independent module Backgroundwatchdog ASYNC was included but not used.
This prevented compilation when ASYNC used function that are not included in
BackgroundWatchdog as well.
=> Removed non required ASYNC include in Backgroundwatchdog

Packages/MIES/MIES_ThreadsafeUtilities.ipf
Restores the original data folder now when before function returns.
Conceptionally ThreadGroupPutDF should work (at the end) like KillDataFolder. However here we had the situation that the current datafolder is a free datafolder and the current datafolder is killed.
The help at KillDataFodler states only:
> However, if dataFolderSpec  is the name of a data folder reference variable that refers to a free data folder, the variable is cleared and the data folder is killed only if this is the last reference to that free data folder.
It is not described what happens if the dataFolderSpec  is actually the current DF.
=> fix undefined current datafolder when exiting TS_ThreadGroupPutVariable

Packages/MIES/MIES_Utilities.ipf
Returning an abolute path to a unique DF name in a free DF is of
limited use, since the ID number of the free DF can not be used with
other functions.
=> UniqueDataFolderName asserts now if dfr is a free DF

Packages/MIES/MIES_Configuration.ipf
Broken since 38b90aba (Configuration: Introduce subgroups and add more
amplifier settings, 2020-01-30).
=> CONF_RestoreHeadstageAssociation: Fix config loading without amplifier

Packages/MIES/MIES_IVSCC.ipf
Close #410.
Functionality requested by @aleonlein.
=> IVS_GetSetQCForSweep: Add convenience function for querying Set QC passed/failed state

Packages/MIES/MIES_Utilities.ipf
Bug introduced in fc842ca2 (Add UploadCrashDumps() with menu entry, 2020-03-05).
We need to go one lever higher compared to the diagnostics folder.
=> UploadCrashDumps: Fix folder moving

Packages/MIES/MIES_DAEphys.ipf
=> DAP_CheckSettings: Avoid using async channels for DAQ as well

Packages/MIES_Include.ipf
this bug was introduced in commit 7b2cd9b9c4ae6d251616dfa13c974a35741f9511
After using any functionality that pushed threaded workloads the data browser
root started to show an empty name. Also the data browser did not update any
more.
closes https://github.com/AllenInstitute/MIES/issues/500
=> Fix for data browser showing empty root data folder after ThreadGroupPutDF

Packages/MIES/MIES_Constants.ipf
Enabling that during DAQ would skip our analysis parameter checking and
we don't want that.
=> DAEphys: Disable the "Skip analysis function calls" checkbox during DAQ

Packages/MIES/MIES_AnalysisBrowser_LabNotebookTPStorageBrowser.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_GuiPopupMenuExt.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/MIES_Include.ipf
The procures try to keep a compatible upgrade, where long popupmenus
get replaced by a button and previous proc definition move to the
buttons userdata.
After the menu finishes the old proc gets called as if it would be a
popupmenucontrol.
See SetupPopupMenuExt() for demo code.
closes https://github.com/AllenInstitute/MIES/issues/228
=> Extended PopupMenus procedures to replace long popup menus

Packages/MIES_Include.ipf
Our new GUIPopupExtension triggered an Igor Pro bug by having long dimension labels in zeroed out dimensions.
The code
```igorpro
Function Dostuff()
Make/O/N=1 data
SetDimLabel 0, -1, $PadString("", 32, 10), data
Redimension/N=0 data
End
```
triggers that crash on save.
Let's require a more recent nightly build to avoid that crash.
=> MIES_Include.ipf: Require the latest nightly build

Packages/MIES/MIES_GuiUtilities.ipf
SetControlValue was working on the current window for a Slider and
not as required on the given target window.
=> fix bug in SetControlValue for Slider working on current window

Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_GuiPopupMenuExt.ipf
The required metadata for the GUI ExtendedPopupMenu was using the
unnamed userdata with a StringByKey list.
This was changed to named userdata where the keys are now the name of
the userdata field.
=> Extended PopupMenu API changed to use named userdata for metadata

Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
In case we have a third party stimset we unconditionally deleted the
stimset. This is disastrous as we can't recreate it as it is a third
party stimset.
Bug introduced in 17809452 (NWB: Change stimset writing logic,
2016-08-17).
=> NWB_WriteStimsetTemplateWaves: Don't kill third party stimsets

Packages/MIES/MIES_MiesUtilities.ipf
Broken since 0cb2be53 (CreateTiledChannelGraph: Show the headstage as
well, 2020-03-30).
=> CreateTiledChannelGraph: Add forgotten window specification

Packages/MIES/MIES_Utilities.ipf
The token waveref is the name of a builtin function in IP9.
=> GetColfromWavewithDimLabel: Rename parameter to avoid IP9 compile error

Packages/MIES/MIES_PulseAveraging.ipf
This makes them more distinguishable from the pink average trace.
=> PA_ShowPulses: Make failed pulses opaque

Packages/MIES/MIES_Menu.ipf
For High-DPI displays, see DisplayHelpTopic "Control Panel Resolution on
Windows", we need to rescale the panel size and the notebook action
scaling.
Verified using 125% scaling, aka ScreenResolution 120, on Windows 10.
=> OpenAboutDialog: Scale the panel and notebook actions correctly

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/Testing-MIES/UTF_Utils.ipf
For reasons yet to be understood the settinsJSONid does sometimes refer
to a non-existing JSON document.
We now regenerate the package settings in this case as well.
=> GetSettingsJSONid: Handle invalid JSON ID

Packages/MIES/MIES_MiesUtilities.ipf
It is just not interesting enough. This also speeds up the PA plot as we
have less data.
Close #161.
=> CreateTiledChannelGraph: Don't display data from TP during DAQ channels

Packages/MIES/MIES_DAEphys_Macro.ipf
The latest IP9 version has finally support for background colors in
checkbox controls. But we are setting some of these values which now
looks odd.
Remove these bogus commands.
Close #603.
=> DAEphys: Remove bogus checkbox colors

Packages/MIES/MIES_IVSCC.ipf
Close #610.
@aleonlein Here you go. I can't find the place in MIES where we deleted the NWB file in the old code before exporting into it. Maybe that was done on the client side (i.e. outside of MIES)?
The patch is based on the 2.1 release, ping my if you need something built on top of master.
=> IVS_ExportAllData: Remove existing NWB files first as requested

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf, Packages/MIES/MIES_Cache.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
Since 378d514f (NumericWaveToList: Make it faster, 2020-08-14) we are
using wfprintf in NumericWaveToList.
Unfortunately this does not work for %d with data beyond 2^31 -1. Until
we have a fix from WaveMetrics we can rely on, let's use ".15g" instead
for all callers.
We also raise the average key version as erroneous cache entries was
what triggerd this bug hunt.
@timjarsky This fixes the buggy pulse average we saw on tuesday.
=> NumericWaveToList: Workaround %d output bug

Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Menu.ipf
Close #630.
This is the bare-bones solution.
I could also create a panel, have a notebook subwindow in that and add a save button on the panel. The save button would allow to check the JSON file for syntax errors. This would catch the most obvious errors.
=> Open config files in notebook

Packages/MIES/MIES_GuiPopupMenuExt.ipf
- Typo fixed in example code in inline documentation
- Special Characters are now disabled for submenu names and menu items, exclusion with :<special>: is still possible when required.
close https://github.com/AllenInstitute/MIES/issues/632
=> Fixes for extended Popup Menu

Packages/MIES/MIES_AnalysisBrowser.ipf
This does not work as we get a HDF5 library error when we try to read
with one file descriptor from it and write into it with another one.
Even if we used the same file descriptors for it, we would need updating
support in the analysis browser to make it really worthwhile using it.
So now we ignore the currently exported into file and warn the user.
Another one from the presentation.
=> AB_ScanFolder: Prevent loading the currently written to NWB file

Packages/MIES/MIES_Async.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_Oscilloscope.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/Testing-MIES/UTF_AsynFrameworkTest.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/doc/asyncframework.rst
- ASYNC_PrepareDF now setups a work load class name as well
- ASYNC_Execute registers now work loads by their class name
- ASYNC_ThreadReadOut tracks now work loads by their class
- ASYNC_IsWorkloadClassDone allows to check if a specific class of work loads
finished. It also allows to remove the work load class when finished.
close https://github.com/AllenInstitute/MIES/issues/101
=> Work load class tracking in ASYNC frame work

Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
The forward and backward resolving by string of the data folder for case 1 was very slow.
We could not reproduce the case in IP7+ where this specific case can cause problems and require this additional check.
We presume it has been fixed in IP.
=> Simplified/SpeedUp DataFolderExistsDFR and Tests

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
- Pulse starting times are in PA_GetPulseStartTimes extracted from the epoch
information stored in the lab notebook
- as fallback the pulse starting times are determined the old direct way
through findlevels.
=> Pulse Averaging: Pulse starting times are now read from the lab notebook (only this)

Packages/MIES/MIES_BrowserSettingsPanel.ipf
In 6140d450 (BSP_MainPanelButtonToggle: Code cleanup, 2020-08-25) the
initialization of panels to "" was erroneously removed.
Instead of fixing it directly, we just the whole code part using it.
It's only reason is to avoid having it being attached to the wrong
panel, and we ensure that already.
=> BSP_ClosePanelHook: Avoid RTE on killVote event

Packages/MIES/MIES_PulseAveraging.ipf
The issue was that for the case that totalOnSetDelay equals the start time of
the first pulse then FindLevels could not detect the first edge any more.
The fix is that FindLevels starts now from totalOnsetDelay - delta.
Start position is capped to be >= 0.
close https://github.com/AllenInstitute/MIES/issues/691
=> Fix for PA_CalculatePulseStartTimes sometimes ignoring the first pulse

Packages/MIES/MIES_PulseAveraging.ipf
The code already expects that in some cases, but not in all.
Fix the latter as well.
This can happen for example if we don't find pulses in a given set.
Close #694.
=> PA_ShowImage: Don't bug out with null setWaves

Packages/MIES/MIES_Async.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_HardwareMain.ipf, Packages/Testing-MIES/UserAnalysisFunctions.ipf
The current code did not expect that you call first without
limitToSetBorder=0 and then with limitToSetBorder=1.
It was also not working for -inf and did not adjust the active set count
correctly when limitToSetBorder=0.
These bugs are now fixed. The solution is to first calculate a skipCount
which is limited to the set borders if requested. And when a new count
is calculated using RA_SkipSweepCalc and the so calculated count offset
is used for adjusting count and the activeSetCount.
=> RA_SkipSweeps: Fix various corner cases

Packages/Conversion/MIES_MassExperimentProcessing.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
When exporting experiments to NWB prior to e96222a6 (TPStorage: Unify on
NOTE_INDEX, 2018-10-17) the TPStorage waves don't have a NOTE_INDEX key.
And the assertion triggers as index is NaN. This was introduced in
c5b1ad32 (NWB_AddDeviceSpecificData: Only write the used rows into the
NWB files, 2020-09-24).
Now we could add a fallback path to try "TPCycleCount" instead. But that
would add a workaround to an optional optimization and is therefore
deemed to complicated.
Therefore we just return the original wave in this case.
=> RemoveUnusedRows: Handle non-existing NOTE_INDEX gracefully

Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
We have a report of a PXP file which has a sweep wave but no config
wave. At this point it is not clear how that can happen, but we need to
allow exporting that data as well.
Reported by Rusty Mann (AI).
This can happen when sweep rollback is used as that was buggy prior to merging #731.
=> NWB_ExportAllData: Handle missing config waves

Packages/MIES/MIES_DataBrowser_Macro.ipf
We don't want that in the JSON configuration.
=> Databrowser: Don't save and restore sweep/step/selector controls

Packages/MIES/MIES_AnalysisFunctions.ipf
Close #734.
@timjarsky I've refrained from using an analysis function parameter for the currently hardcoded targetVoltages  wave. But I could also do that.
=> Port ReachTargetVoltage to V3 and fix RTE

Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_OverlaySweeps.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/Testing-MIES/UTF_Utils.ipf
We have one x axis  and scale bar for each region (column). In order to
not clutter the image we only add one x scale bar the bottom right set.
We allow users zoomming in and out into each x axis, and then
dynamically resize the x scale bar to a fitting length.
This makes it really hard to know the exact physical length when
zooming.
We solve that by remembering the initial x bar length and always draw
the x bar length if it is different from the inital value.
Close #696.
Close #698.
=> PA_DrawScaleBarsHelper: Draw x scale bar length if different

Packages/MIES/MIES_PulseAveraging.ipf
In PA_LayoutGraphs the trace plot is set to draw lines between points.
Profiling shows that this uses up a lot of time.
On the other hand drawing lines between points is the Igor default.
So unless a user changes the drawing mode, this change has no effect
but a notable speedup.
Found with a better adapted profiling routine.
=> PA: Speed optimization in PA_LayoutGraphs

Packages/Testing-MIES/UTF_HardwareMain.ipf
With the updated UTF we now have a proper order for the test cases and
test suites.
So let's reorder them from basic to fancy.
=> Hardware Tests: Reorder test suites

Packages/MIES/MIES_PulseAveraging.ipf
Using an uninitialized variable all vertical axes were distributed to zero, thus on the left edge of the graph.
=> PA: bugfix vertical axes in trace/image plot were not distributed properly

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_OverlaySweeps.ipf, Packages/MIES/MIES_Structures.ipf
This increases the speed when the DataBrowser graph is updated.
The same logic as in the grouped drawing for the PA plot is used,
with the expension that a structure is introduced to carry the draw
information. This allows to draw the graph elements at a later point in
the code.
close https://github.com/AllenInstitute/MIES/issues/749
=> DataBrowser: Added grouped drawing when sweeps are added.

Packages/MIES/MIES_Debugging.ipf
That debug function creates a two column wave, where the second column
holds the size in MB of the wave.
But just using that column for sorting does not work with floating point
values converted to strings. By using the original wavesize wave with
floating point numbers we can fix that.
=> GetSizeOfAllWavesInExperiment: Fix sorting by ascending wave sizes

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_OverlaySweeps.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_PA_Tests.ipf
Previously HS removal only removed the associated channel of the set sweep but left all other regions in the plot.
Removed expected failure from test.
close https://github.com/AllenInstitute/MIES/issues/729
close #737
=> Fixed: PA plot HS removal now removes also the same regions in the vertical direction

Packages/Testing-MIES/UTF_HardwareMain.ipf, Packages/Testing-MIES/UTF_VeryBasicHardwareTests.ipf, Packages/Testing-MIES/UserAnalysisFunctions.ipf
We create in MIES a file with the same name for user analysis functions.
This can lead to difficult to diagnose error message when that file is
included instead of the correct one.
Fix that by using a version for the correct file and also have a test
which searched for a marker function.
=> Packages/Testing-MIES/UserAnalysisFunctions.ipf: Mark it as special

Packages/MIES/MIES_ProgrammaticGUIControl.ipf
This assertion message is in the top 10% for users. So let's be a little
nicer and tell them which window and control was missing.
Close #774.
=> PGC_SetAndActivateControl: Give a better assertion message

Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveBuilder.ipf, Packages/MIES_Include.ipf, Packages/Testing-MIES/UTF_Utils.ipf, tools/clean_mies_installation.sh
Packages/MIES_Include.ipf: Lower IP9 nightly version:
Only this is available on one of the CI boxes.
Close #745.
=> Add CI support for IP9

Packages/MIES/MIES_WaveBuilderPanel.ipf
If we have selected a analysis function we should just jump to it,
instead of blindly opening UserAnalysisFunctions.ipf.
This is especially convenient for the builtin PSQ/MSQ analysis
functions.
=> WBP_ButtonProc_OpenAnaFuncs: Open the function directly if possible

Packages/MIES/MIES_DAC-Hardware.ipf
=> HW_GetDeviceInfo: Allow compiling with older NIDAQmx XOPs

Packages/MIES/MIES_MiesUtilities.ipf
…execution
Since forever we did not set the dialogsOK parameter for the background
tasks. And the default is dialogsOK = 1 which means that dialogs can run
during background execution.
The Igor help is pretty clear on that, that this can cause crashes when
removing traces from a graph etc.
And that can happen as we call SWS_SaveAcquiredData from the DAQ
background functions and user analysis function as well.
So let's disable that.
Found with user uploaded crash dumps and help from Adam Light
(WaveMetrics).
=> SetupBackgroundTasks: Don't allow dialogs during background function … [Backport]

Packages/MIES/MIES_Menu.ipf, Packages/MIES_Include.ipf, tools/unit-testing/check_mies_compilation.sh
The background watcher panel is a debugging tool for background tasks.
And therefore by the average user not used at all.
And as it is living in an independent module there is always the chance
that you edit the wrong include file when developing.
So let's not include it by default but only on request.
This also makes compilation faster.
=> Only compile the background watcher panel when required

Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_OverlaySweeps.ipf
We used to select the first sweep if nothing is checked for overlay sweeps. But that is counter-intuitive, so let's check the current sweep instead.
Accompanying fix to 34d00ea9 (OVS_ChangeSweepSelectionState: Avoid always selecting the first sweep, 2020-10-30) and 2e6e9e4e (OVS_UpdatePanel: Fix OVS enabling selecting the very first sweep, 2020-11-13).
Close #817.
=> OVS_UpdatePanel: Select the current sweep when enabled

Packages/MIES/MIES_ExperimentDocumentation.ipf, Packages/Testing-MIES/UTF_AnalysisFunctionHelpers.ipf
Since 22a7af4a (ED_createTextNotes: Store sub-second precision in
Timestamp columns, 2017-10-12) we use num2str instead of num2istr for
storing the DateTime in the textual labnotebook.
The intentation was to store timestamps with sub-second precision.
But that change was wrong as Igor outputs only 5 relevant digits for
double when converted to a string as shown in the following example:
•print/D num2str(Datetime)
3.6968e+09
•print/D num2istr(Datetime)
3696770484
So we need to use num2strHighPrec with precision 3 which gives
timestamps with millisecond resolution.
=> ED_createTextNotes: Store timestamps with enough resolution

Packages/MIES/MIES_MiesUtilities.ipf
This is flagged with IP9 r36973 and later. And it is totally correct
that we have to pass convert the sweep numbers when extracting them from
the textual labnotebook.
The bug resulted in the wrong sweep numbers being reported in case these
were not purely ascending starting from 0.
=> GetSweepsWithSetting: Don't treat textwaves like numeric waves

Packages/MIES/MIES_PulseAveraging.ipf
In the PA plot we support looking at the region slider to adjust the
displayed regions.
But if the region slider is active we skip over some regions. And for
finding the first graph we then must not compare not against zero, but the
first region we did not skip.
Close #844.
I'm still puzzled why we plot the average data for the non-selected regions. Is that something you want?
=> PA plot: Get the correct graph with non-default region slider

Packages/MIES/MIES_PulseAveraging.ipf
We start with the value of NaN to indicate that we don't care about the
number of spikes. But that also makes the up/down buttons useless as NaN
+/- 1 is always NaN again.
So let's use 1 in this case instead.
Close #820.
=> PA_SetVarProc_Common: Allow escaping NaN for number of spikes controls

Packages/MIES/MIES_AmplifierInteraction.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_HardwareMain.ipf
Close #860.
Close #850.
We still respect "Mode switch via I=0" when changing clamp mode for the auto pipette offset function. Is that correct?
=> Fix autopipette offset taking apply on mode switch into account

tools/clean_mies_installation.sh
With the "installer" installation we currently install MIES for each
version with the installer. But that is not necessary as the installer
installs for all available and supported IP versions.
This also fixes an edge case where the installer fails with return value
2 as it still finds an existing IP9 version when installing for IP8 in
the loop.
We also remove the platform dependent special casing for MINGW and
others. We only support Windows/Mingw nowadays.
=> tools/clean_mies_installation.sh: Fix edge case and speed up

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_PressureControl.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_HardwareMain.ipf
Close #849
Close #842
Close #131
Close #880
=> P_RecordUserPressure: Make read errors fatal

.gitattributes
We actually need to use ** as only that recurses into subdirectories.
Not properly done in 86575bf7 (.gitattributes: Mark more paths as non
source code for github, 2021-01-27).
=> .gitattributes: Fix linguist overrides

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_IgorHooks.ipf, Packages/MIES/MIES_Logging.ipf, Packages/MIES/MIES_PackageSettings.ipf
Since c87daee1 (MIES_PackageSettings.ipf: Extract settings folder
creation into separate function, 2021-03-09) we created the log file and
the JSON settings file in the folder
C:\Users\$user\AppData\Roaming\WaveMetrics\Igor Pro 8\Packages
instead of
C:\Users\$user\AppData\Roaming\WaveMetrics\Igor Pro 8\Packages\MIES
.
The reason is that the path contained an additional colon (":") which in
IP lingua means "go down one folder". But that was only the case in IP8,
IP9 has a bug where this was is not done.
Remove the additional colon so that it works with all IP versions.
@timjarsky I don't have a automatic fix, which means that we move the files from the wrong location to the right location, included. Should I?
=> Fix package folder location on disk

Packages/MIES_Include.ipf
This resolves the slow compilation issues with the navigation bar
enabled and might also avoid the minute long lockup then NewExperiment
is called.
Close #912.
We nearly had for one year the same IP8 nightly. Glad I "fixed" that.
=> MIES_Include.ipf: Raise required IP8 version

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DataAcquisition.ipf, Packages/MIES/MIES_DataAcquisition_Multi.ipf, Packages/MIES/MIES_DataAcquisition_Single.ipf, Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_ExperimentDocumentation.ipf, Packages/MIES/MIES_IgorHooks.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_RepeatedAcquisition.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/MIES/MIES_TestPulse_Multi.ipf, Packages/MIES/MIES_TestPulse_Single.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_HardwareMain.ipf
`DQ_STOP_REASON_BUTTON` -> `DQ_STOP_REASON_DAQ_BUTTON`
This fixes point 2 of #798.
=> Document daq stopping reason

.gitmodules, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DAEphys_GuiState.ipf, Packages/MIES/MIES_Debugging.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_SweepSaving.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_HelperFunctions.ipf, Packages/Testing-MIES/UTF_Utils.ipf
Calling NWB_ExportAllData where at least one device has content but no
sweeps currently leads to NWB_CheckForMissingSweeps bugging out as
GetSweepsWithSetting returns a null wave.
Bug introduced in 6a432cb7 (Add code to allow recovering deleted sweeps,
2021-04-19).
=> NWB_CheckForMissingSweeps: Handle no sweeps gracefully

tools/nextFreePRNumber.sh
Discussion on github share the same number space as issues and PRs.
Unfortunately we can not just query the list of discussions using the
REST API as there only exists a GraphQL API and that needs always
authentication.
So let's just use dump curl to find the first discussion ID which return
a HTTP status code different than 200.
=> tools/nextFreePRNumber.sh: Make it work with discussions

Packages/Conversion/MIES_MassExperimentProcessing.ipf, Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_IVSCC.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_TestNWBExportV1.ipf, Packages/Testing-MIES/UTF_TestNWBExportV2.ipf, Packages/Testing-MIES/UTF_Utils.ipf
Close https://github.com/AllenInstitute/MIES/issues/911
=> Allow resaving NWBv1 files into NWBv2 files

Packages/MIES/MIES_Oscilloscope.ipf
The name of the DAQDataWave is not the same anymore as the wave
reference name  since 1776cd86 (GetDAQDataWave: Introduce separate waves for DAQ/TP, 2020-12-15).
=> SCOPE_ITC_UpdateOscilloscope: Fix debug mode

Packages/MIES/MIES_WaveDataFolderGetters.ipf
Not setting the wave version results in both cases code being executed
which could have been avoided. No other problems are present, it is only
slower as it could be.
So let's set the wave version.
Found with UTF tracing.
Close #1009.
=> GetChanAmpAssignUnit/GetValidAcqStateTransitions: Fix performance bugs

Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
This adds the following TTL labnotebook entries:
- Stimset length
- Stimset checksum
- Stimset wave note (URL encoded)
- Indexing end stimset
They are stored in a hardware agnostic way with NUM_DA_TTL_CHANNELS
entries per INDEP_HEADSTAGE layer entries.
Close #798.
=> Add more TTL labnotebook entries

Packages/MIES/MIES_BrowserSettingsPanel.ipf
Forgotten in f79e3e54 (Dashboard: Show the result message as tooltip for all columns, 2021-04-30).
The Databrowser macro was now with that change regenerated without
raising its version.
=> BSP_UnsetDynamicStartupSettingsOfDataBrowser: Unset dashboard help wave

Packages/MIES/MIES_MiesUtilities.ipf
The returned string is null in case the ZeroMQ XOP is not present.
As we don't use the return value anywhere we can just remove it. Bug
introduced in 7fd21c6b (Set a custom logging template for the ZeroMQ-XOP, 2021-04-12).
=> UpdateZeroMQXOPLoggingTemplate: Remove bogus returned string

Packages/MIES_Include.ipf
This fixes a crash in the BeforeUncompiledHook.
Close #1026.
=> IP9: Raise required version

.gitattributes, tools/clean_mies_installation.sh
Ever since we dropped the ITCXOP submodule in 254b1bca (Readd needed
ITCXOP2 scripts, 2021-04-08) we did not include the ITCXOP tools
directory in the release package.
This was due to export-ignore tag on all directories named tools.
We now readd Packages/*/tools as we want this.
=> Make release package installation work again

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_Debugging.ipf, Packages/MIES/MIES_ExperimentDocumentation.ipf, Packages/MIES/MIES_StimsetAPI.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/MIES_Include.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_Labnotebook.ipf, Packages/Testing-MIES/UTF_StimsetAPI.ipf
=> Make dimension labels valid liberal object names

Packages/MIES/MIES_SweepFormula.ipf, Packages/Testing-MIES/UTF_SweepFormula.ipf, Packages/doc/SweepFormula.rst
The code that failed:
```
abcd vs 2
```
The issue was that the "vs" token for plotting was processed before the
comments were processed in the state based parsing. Since the "vs" token is
parsed with a regex the parsing can not be simply swapped.
Fix: Before the formula is parsed it is preprocessed where based on a per line
basis the comments after # are removed.
The same step is used to unify the line endings to CR by replacing LF with CR.
(CR LF -> CR CR adds an empty line, but the state based parser ignores empty
lines)
The comment handling in the state based parser was removed.
As testing calls the Formula Parser function directly some additional code was
introduced to execute the preprocessing then there.
close https://github.com/AllenInstitute/MIES/issues/1054
=> Sweepformula did not process comments with # correctly

Packages/MIES/MIES_Configuration.ipf
We currently have the slider position at the first non-configured
headstage after configuration.
As this is quite confusing we now switch back to the very first
headstage. This also is more convenient for the not-too-small crowd only
acquiring data on one headstage.
Close #1068
=> CONF_RestoreDAEphys: Switch back to Headstage 0 after configuration

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_WaveBuilder.ipf, Packages/Testing-MIES/UTF_Epochs.ipf
EP_AddEpochsFromStimSetNote was also called for stimsets with empty wave notes
such as TP during DAQ stimsets. This resulted in an ST_B (stimset baseline)
epoch added for this stimset, that is wrong.
Fix: - Added a check in callers of EP_AddEpochsFromStimSetNote to call only if
the stimset is of a type that should contain epoch data.
- Added better checks in EP_AddEpochsFromStimSetNote
- increased sweep_epoch_version.
close https://github.com/AllenInstitute/MIES/issues/1063
=> fix EP_AddEpochsFromStimSetNote for empty stimset wave notes

tools/sign-installer.sh
Requires a EV certificate on a USB token and the Safenet Client
Application.
=> Add script to sign the installer [backport]

Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_Utilities.ipf
Panel resize information was saved automatically by calling
SaveControlPositions from Igors own ResizeControlsPanel package.
However there was a wave referenced that did not exist, resulting in an RTE.
The RTE did not influence the correct execution.
This commit fixes the RTE by creating the required wave beforehand.
since 522082999cb4aea1c2252886995720d24ada9df0
and 74cc953eacd7c3d2a603806ad48fd639eac98832
close https://github.com/AllenInstitute/MIES/issues/1076
=> fix to store resizeInfos automatically without pending RTE

Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_Utils.ipf
The issue triggering this [1] claimed that IsConstant does not work with
NaN in the input.
But actually the current behaviour was just to ignore NaNs in the input,
which also all callers relied on.
We now have the option to not ignore NaNs in the input.
We also fixes edge cases for empty input waves (return NaN) and the case
were all input is NaN and we ignore NaN. The latter now gives NaN as this is
equivalent to an empty input wave.
[1]: https://github.com/AllenInstitute/MIES/issues/1124
Close #1124.
=> IsConstant: Allow to not ignore NaNs and fix edge cases

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_OverlaySweeps.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_TestNWBExportV1.ipf, Packages/Testing-MIES/UTF_TestNWBExportV2.ipf
=> Databrowser set sweep count selection

.gitignore
This also catches the new naming scheme introduced in 989fa8ff (UTF_TestNWBExportV1.ipf: Use -V1 suffix for NWB files, 2020-02-09).
=> .gitignore: Ignore all NWB files in tools/testing

Packages/MIES/MIES_AmplifierInteraction.ipf, Packages/MIES/MIES_Blowout.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf, Packages/MIES/MIES_DataAcquisition.ipf, Packages/MIES/MIES_DataAcquisition_Multi.ipf, Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_ExperimentDocumentation.ipf, Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_IVSCC.ipf, Packages/MIES/MIES_Oscilloscope.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/MIES/MIES_TestPulse_Multi.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf, Packages/Testing-MIES/UTF_HardwareMain.ipf, Packages/Testing-MIES/UTF_Main.ipf, Packages/Testing-MIES/UTF_Testpulse.ipf, Packages/doc/TPAnalysis_algorithm.rst
This is a preparational PR for #1016.
Close #1015.
=> Testpulse waves cleanup

Packages/MIES/MIES_DAEphys.ipf
Ever since d1c250ca (DAP_SerializeCommentNotebook: Add user comment from set variable, 2021-10-02)
ba83aae3 and (DAP_SerializeCommentNotebook: Call it before exporting the comment into NWB, 2021-10-02)
we do call DAP_AddUserComment() from the NWB export path.
But that also means that the pxp could be reopened and therefore the original
device window not being open anymore.
Let's just not do anything here in this case.
Closes #1134.
I can export the pxps with that fix.
@sfowen Does that fix the issue for you as well?
=> DAP_AddUserComment: Handle non-existing window

Packages/MIES/MIES_SweepFormula.ipf
When plotting multiple graphs in a panel then the wave with the
x-values were not properly cleared and thus reused on a following
plot where no X-values were specified.
This wave is now properly cleared.
since b257f7999e7b6445e116b33140dbc18dba9558a9
Close https://github.com/AllenInstitute/MIES/issues/1160  :sparkles:!
=> bugfix SweepFormula use of previous X-values in multi-plot

tools/sign-installer.sh
This makes CI fail when the signing fails.
Broken since 7399680d (tools/sign-installer.sh: Add script to sign the
installer, 2021-09-24).
=> tools/sign-installer.sh: Return error code from sign_tool

Packages/MIES/MIES_LogbookViewer.ipf
The default x axis of the logbook graph was always "sweeps". This is
good for acquired sweep data.
But if you play around with TP only, you currently don't see anything
when adding an entry as there are no sweeps, and plotting something
against NaN does not create anything in the graph.
So let's use a time axis if we don't have sweeps.
=> LBV_CheckIfXAxisIsTime: Tweak default value depending on existing sweeps

Packages/doc/developers.rst
This PR tested the new CI config to prevent test runs by including the [SKIP CI] tag in a commit message.
Added documentation to describe the new key word for commit messages that inhibits test runs on the CI (bamboo).
=> Docu for CI hints to inhibit tests

tools/build-documentation.sh
- output folders xml, struct, group, file, namespace, _images and html
are cleaned to the checked-in files only before a new build is attempted.
=> Documentation: Clean docu output folders on new documentation build

Packages/MIES/MIES_ArtefactRemoval.ipf, Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_LogbookViewer.ipf, Packages/MIES/MIES_OverlaySweeps.ipf, Packages/MIES/MIES_SweepFormula.ipf
The MIES code had locations where BSP_GetLBNWave was used without properly
checking if the returned wave is a null wave.
Occurrences with that flaw were reviewed and adapted to react properly to
a returned null wave.
=> fix wrong usage of BSP_GetLBNWave, return wave requires check against null wave

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
to TP Amplitude VC: pA
TP Amplitude IC: mV
The units are required for axis labels of graphs that show this data,
e.g. in DataBrowser.
We want to show in graphs to correct units on the axes, so we need the unit names for certain values somewhere in MIES. A good location is the LBN, because it allows to retrieve the units from the time the value was created.
=> LBN: Add units to TP settings entries

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf, Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/Testing-MIES/UTF_TestNWBExportV1.ipf, Packages/Testing-MIES/UTF_Utils.ipf
After a discussion with Thomas about the disadvantages of isEmpty when using strings from structures or text wave elements we decided to give this change a try.
Since Igor generates a RTE if a null string is used as parameter as a non-ref parameter isEmpty will now generate an RTE if it is used to check against a null string. (Where IsNull should be used). Despite the RTE it will still work correctly for the case of a null string parameter though.
CI will hopefully show locations in the code where such lingering RTEs are generated.
=> Change isEmpty to not use string parameter by reference

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf, Packages/MIES/MIES_Constants.ipf
When going from milli to unity the factor is 1e-3. Bug introduced in
0a86df51 (PSQ Analysis functions: Store the baseline voltage when
evaluated, 2021-01-15).
=> [Backport] PSQ_EvaluateBaselineProperties: Fix scale of average voltage

Packages/MIES/MIES_MiesUtilities.ipf
When acquiring oodDAQ data and when trying to view the data with dDAQ
checkbox enabled and AUTOMATED_TESTING being defined, we get an assertion from
EnforceIndependentSetting introduced in d0dfc2e8 (Labnotebook: Enforce
that the INDEP getters are correctly used, 2021-04-22).
We can avoid that by querying the INDEP_HEADSTAGE entry of "Stim set
length" only when dDAQ is enabled, as it is in the headstage dependent
entries for all other cases.
=> CreateTiledChannelGraph: Fix assertion with dDAQ slider

Packages/MIES/MIES_DAEphys_Macro.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_WaveBuilder_Macro.ipf
This is a preparation PR for an upcoming update of the unit-testing framework.
Procedure files that contain only macros require to have at least one
function for the unit-testing framework to apply instrumentation.
The additional function have no body and are not called, they just serve to
overcome the Igor Pro limitation that allows to retrieve the file system
location of procedure files through FunctionInfo. Though, FunctionInfo works
only with function names.
=> Add instrumentation helper function for macro-only procedure files

Packages/doc/developers.rst, tools/unit-testing/check_junit_xml_files.sh
We have a report [1] that failing tests with ITC1600 hardware results in
invalid JUNIT files due to invalid UTF8-characters.
A preliminary analysis suggests that the problem is some kind of memory
corruption.
In order to debug that issue, we now check all generated JUNIT XML files
during CI are XML-compliant.
autorun-test.sh is used by all jobs which execute tests.
[1]: https://github.com/byte-physics/igor-unit-testing-framework/issues/236
=> tools/unit-testing: Check JUNIT xml files

Packages/MIES_Include.ipf
Due to repeated crashes on the ITC CI box [1], the author of this commit
chatted with WM support about potential remedies.
And it turns out some quick fixes should already make it less likely
crashing and also avoids the billion explorer windows on bug messages.
So let's require the IP9 nightly from today.
Let's see what CI says.
Close #1311.
=> Require newer IP9 version

Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DebugPanel.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES_Include.ipf, Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
This has a fix which is supposed to be responsible for at least 1/3 of
the crashes between 8/2021 and 4/2022.
=> MIES_Include.ipf: Raise required IP9 version [Backport]

Packages/MIES/MIES_LogbookViewer.ipf
At the very beginning of the labnotebook in MIES we treated the last
layer as the "all" entry for all headstages. This was very quickly
abandoned in favour of the concept of having headstage independent
entries stored there instead.
We therefore now rename the legend in the logboook viewer from all to indep.
=> LBV_UpdateLBGraphLegend: Tweak legend

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_GuiUtilities.ipf
We actually only need to call it once, as it is a global setting and not a
per-graph setting.
Doing it in BSP_InitPanel is close enough.
Close #1364.
Close #1280.
=> ShowTraceInfoTags: Call it only once per Databrowser

Packages/Testing-MIES/UTF_HardwareMain.ipf, Packages/Testing-MIES/UTF_PatchSeqAccessResistanceSmoke.ipf, Packages/Testing-MIES/UTF_PatchSeqPipetteInBath.ipf, Packages/Testing-MIES/UTF_PatchSeqSealEvaluation.ipf, Packages/Testing-MIES/UTF_PatchSeqTrueRestingMembranePotential.ipf
Up to now we had in each test case a check for the set stimulus set names
in the POST_SET_EVENT, see PSQ_SetStimulusSets.
We now generalize the tests so that in the future we can also
automatically reuse these tests for analysis functions supporting these
analysis parameters.
The uncontroversial parts of #1362.
=> Generalize checks for NextStimsetName/NextIndexingEndStimsetName

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Although our analysis functions don't handle manually stopped sweeps
properly, the dashboard at least does not have to show BUG messages for
them.
Reported in https://aiephys.slack.com/archives/G01CZ45S95X/p1653074308896399?thread_ts=1653068335.340289&cid=G01CZ45S95X.
=> AD_GetPerSweepFailMessage: Handle manually stopped sweeps

Packages/MIES/MIES_ExperimentDocumentation.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
This was found as part of testing #1380. This fixes the "BUG: ED_FindIndizesAndRedimension" messages. This bug should not influence normal users as you have to acquire data with one MIES version and then acquire data with a newer MIES version again into the same file. Nevertheless worth fixing.
=> Fix labnotebook description wave not being refetched if changed

Packages/MIES/MIES_AsynchronousData.ipf, Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_MiesUtilities.ipf
That is a bummer!
We actually did not support NI hardware for async channels. I found that by accident when I looked at some other CI failure. What put me off was that we had some ITC errors in the NI hardware tests, see [1].
The test case AsyncAcquisitionLBN works with NI hardware but had this output.
```
<testcase name="AsyncAcquisitionLBN:NI in UTF_BasicHardwareTests.ipf (4)" classname="AsyncAcquisitionLBN:NI" time="15.161">
<system-out>
Entering test case "AsyncAcquisitionLBN:NI" The ITC XOP returned the following errors: ITCError=0x82503001, ITCXOPError=0 System is not initialized (0x82503001);Place: User Layer; Connection: DSP; Error Type: Ready; Sequence Number: 0x0; Device Type: ITC1600; OS: Any; Application: Regular; Local Sequence Number: 0x1 Some hints you might want to try! - …
```
=> Make async channels work with NI hardware

Packages/MIES/MIES_WaveBuilderPanel.ipf
Igor Pro currently does not store dimension labels for non-existing
dimensions. This means that column labels don't survive experiment saving
and loading if the row count is zero.
For the Wavebuilder this affects WBP_GetAnalysisParamGUIListWave and
friends.
The easiest solution is to throw away any existing waves on panel creation.
=> WBP_ClearFolders: Factor out helper function

Packages/doc/mies-concepts.rst, README.md
Forgotten in 3a1b477 (Packages/MIES_Include.ipf: Remove support for Igor
Pro 8, 2022-04-15).
=> README.md: Mention Igor Pro 9 instead of 8

tools/nwb-read-tests/run.sh
Released in March 16 2022, see
https://github.com/NeurodataWithoutBorders/pynwb/releases/tag/2.0.1.
Merge once CI passes.
=> tools/nwb-read-tests/run.sh: Update pynwb version

Packages/Testing-MIES/UTF_HardwareMain.ipf
When assembling the procedure file list for RunTest two procedure files
were added at the beginning of the list instead of the end.
This resulted in an unwanted execution order of the test suites.
Now they are properly added at the end of the list.
=> Tests: Fix that hardwaretest testsuites were not properly sorted

Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
We currently only check if the primary and secondary gains are unity. But
since daddd566 (AI_SendToAmp: Add some more MCC functions, 2022-04-05) we
can actually set them as well.
So let's do that. This fixes CI errors when the gain was changed by other
tests.
=> Tests/EnsureUnityGain: Set the gain

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf
This was not respected on Windows until r39013, but we actually just want
the default color.
The fix in IP as it is today also changes the style of the thumb on color
change.
Merge once CI passes.
=> DA_Ephys: Remove thumbColor keyword

Packages/Testing-MIES/UTF_HardwareMain.ipf
=> Hardware Tests: Change default ITC1600 device

tools/clean_mies_installation.sh
When skipping hardware XOPs we have a list of files to install. This list
was not updated in 65994377 (Add TUFXOP for IP9-64bit, 2021-06-26).
=> tools/clean_mies_installation.sh: Install TUF XOP for release package

Packages/MIES/MIES_MiesUtilities.ipf
We don't convert to integer, but instead throw away anything below
microseconds.
Close #1333
=> GetSamplingIntervalFromLBN: Fix comment

tools/clean_mies_installation.sh
Since forever we are just installing the new MIES version on top of the
old one. This can create problems if two XOPs from different branches
export the same operations/functions. And this is the case since 69a22f1b
(XOPs: Update TUF XOP to the released version, 2022-07-25) got merged.
The '/CIS' installation mode does not uninstall the already existing
version, so we need to do that ourselves here.
=> tools/clean_mies_installation.sh: Remove old MIES installations

Packages/MIES/MIES_Structures.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/Testing-MIES/UTF_SweepFormulaHardware.ipf, Packages/Testing-MIES/UserAnalysisFunctions.ipf
The duration is in points and not in ms as the code assumed.
Bug introduced in the initial version in 044d386 (SweepFormula add tp
operation, 2021-12-09).
=> SF_OperationTP: Fix TP property calculation [backport]

Packages/MIES/MIES_Structures.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/Testing-MIES/UTF_SweepFormula.ipf, Packages/Testing-MIES/UTF_SweepFormulaHardware.ipf, Packages/Testing-MIES/UserAnalysisFunctions.ipf
The duration is in points and not in ms as the code assumed.
Bug introduced in the initial version in 044d386 (SweepFormula add tp
operation, 2021-12-09).
Close #1273
Close #1444
=> SF_OperationTP: Fix TP property calculation

Packages/MIES/MIES_AcquisitionStateHandling.ipf, Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
This fixes an issue where the ongoing DAQ state was incorrectly reported for stimsets without analysis functions attached.
Minimal backport version of #1453.
=> Dashboard fix

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_IgorHooks.ipf
When opening a saved experiment we don't re-execute the BSP_InitPanel code.
And the only place which we know is always executed are the Igor hooks.
The hooks IgorStartOrNewHook/IgorBeforeNewHook don't work, so we use
AfterCompiledHook.
This complements the fix from da7cc293 (ShowTraceInfoTags: Call it only
once per Databrowser, 2022-05-10).
=> ShowTraceInfoTags: Call it always

Packages/Testing-MIES/UTF_Labnotebook.ipf
In the upcoming IUTF update the data generator waves are retrieved once at the start of the testrun. Thus, the test must make sure that the wave is actually constant and not killed in between the retrieval and the test case execution.
=> WIP: Test adaptations for upcoming IUTF update

Packages/MIES/MIES_DAEphys.ipf
Since 9293eac6 (DA_Ephys: Add a button to the hardware tab allowing to
clear the channel/amplifier connections, 2015-12-16) we allow to clear the
headstage/channel association.
But in cb206d3c (GetChannelClampMode: Extend to also hold headstage
information, 2019-03-08) we introduced the channel clamp mode wave which
also holds the headstage/channel association.
This needs to be cleared as well.
=> DAP_ButtonProc_ClearChanCon: Also clear the channel clamp mode wave

Packages/MIES/MIES_SweepFormula.ipf, Packages/Testing-MIES/UTF_SweepFormulaHardware.ipf
SF_GatherFormulaResults has a logic to determine if data units should be shown in the final formula plot or not. The string that is used to check for the presence of valid data units was not handled correctly. For the special case that no data wave are present, the IsEmpty test after the skipped loop over all data waves generated an RTE.
introduced in 74d4d3c8a5b530390e25715ca28c3609168e4a86
=> SF: Fix RTE at check for dataUnit with no data waves in SF_GatherFormulaResults

Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
These are broken since df0fc1e2 (UTF_BasicHardwareTests.ipf: Use new AcquireData approach, 2022-09-25).  CI had them also passing sometimes...
=> tests/UTF_BasicHardwareTests.ipf: Fix some tests

Packages/doc/developers.rst, Packages/tests/UTF_HardwareHelperFunctions.ipf, Packages/tests/UTF_HelperFunctions.ipf
The environment variables BAMBOO_EXPENSIVE_CHECKS and BAMBOO_INSTRUMENT_TESTS can now also be used to turn the feature off.
This allows to execute some tests faster in CI.
We also introduce GetEnvironmentVariableAsBoolean as helper function.
=> Tests: Allow tweaking test execution more fine-grained

Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/tests/Basic/UTF_Configuration.ipf
This enhances the MIES Configuration module to be aware of notebook windows.
For notebook windows the content gets saved as plain text and restored as plain text.
The SweepFormula help notebook was excluded from saving/restore as it contains formatted text.
close https://github.com/AllenInstitute/MIES/issues/646
=> MIES Configuration, enhance to save/restore also notebook contents as plain text

Packages/MIES/MIES_IgorHooks.ipf
if MIES is included in Igor Pro and the user has an experiment loaded from a read-only location then the SaveExperiment call in the Hook creates a runtime-error that could pop up the Debugger.
Thus, if Igor Pro is quitting and the experiment can not be saved, we ignore the error from the save attempt.
=> bugfix in IgorBeforeQuitHook ignore error on SaveExperiment

Packages/Conversion/MIES_MassExperimentProcessing.ipf, Packages/MIES/MIES_ThreadedFIFOHandling.ipf, Packages/MIES/MIES_ThreadsafeUtilities.ipf, Packages/doc/MIES_Regenerate-Screenshots.ipf, Packages/tests/Basic/UTF_Basic.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqChirp.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_ReachTargetVoltage.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_SetControls.ipf, Packages/tests/PAPlot/UTF_PAPlot.ipf, tools/check-code.sh
We now enforce that we always have rtGlobals=3, rtFunctionErrors=1,
TextEncoding and a ModuleName/IndependentModule pragma.
Close #1477 
=> Unify pragma usage and add checks

Packages/MIES/MIES_DataConfigurator.ipf, Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
Broken since fce6612d (DC_PlaceDataInHardwareDataWave support for TPwhileDAQ on DAC channels, 2019-01-04).
Close #1517.
=> DC_GetConfiguration: Handle oodDAQ with only TP during DAQ channels

Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf, Packages/tests/Basic/UTF_Utils.ipf
When only sweep numbers change in the legend of the sweepformula plot then the numbers are joined in a comma separated list.
Only one line is shown in the graph legend.
close https://github.com/AllenInstitute/MIES/issues/1470
=> SF: Shrink legend text if only sweep number changes

tools/initial-repo-config.sh
Since e0d04315 (.gitmodules: Clone the submodules shallowly, 2021-04-08) we clone the submodules shallowly to speedup CI.
Cloning a repository shallowly creates the fetch refspec
+refs/heads/<defaultbranch>:refs/remotes/origin/<defaultbranch>
And due to this refspec it is not possible to fetch other branches.
By adjusting the refspec of all submodules to the default one, we allow fetching other branches as well. This is not detrimental for CI as the shallow clone of the submodules is already done once this script is run.
@MichaelHuth This should solve the issue that on MIES repo clones the submodules can not fetch other branches.
=> tools/initial-repo-config.sh: Adjust the fetch refspec

Packages/MIES/MIES_AmplifierInteraction.ipf
We occasionally have CI errors when AxonTelegraphGetDataStruct fails. As
this seems to be a transient error, we can just wait for 100ms and retry
in these cases.
Close #1510
=> AI_GetTelegraphStruct: Repeat on error

Packages/MIES/MIES_IgorHooks.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_TestPulse.ipf
MultiThreadingControl allows to adjust when automatic threads are created for calculations.
The default (mode = 1) does use automatic threads only in the main thread. From other projects we know that this can be a limitation which is difficult to realize and thus lift.
Let's choose mode == 4 which uses automatic threads also in explicit/preemptive user threads.
Close #1512.
=> AfterCompiledHook: Use more threads

Packages/MIES/analysis_function_parameters.itx, Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf
The recently added test added in 39178e5 (Documentation/Tests: Add table with all analysis parameters, 2022-10-30) did cross with 58d4c2b (PSQ_SquarePulse: Remove unused analysis parameters, 2022-10-23) which removed an unused analysis parameter.
Regenerate the table and fix that.Thanks for opening a PR in MIES :sparkles:!
=> Tests: Fix GenerateAnalysisFunctionTable

Packages/tests/Basic/UTF_AsynFrameworkTest.ipf
Originally the WARN(1) was intended to generate a output message if the test for orderless execution resulted in an ordered workload output. (There is a chance that this happens)
However, only WARN(0) ever creates an output message.
This is fixed with this commit.
since 601010fcb05670b1689bb2b317ec0382284d0b93
close https://github.com/AllenInstitute/MIES/issues/1539
=> Asyn: Fix WARN(1) in tests for orderless execution

Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf
- the plotter can only plot text wave data when an corresponding x-wave is given. This was not checked properly, such that an RTE was generated for simple 1d text waves as input without an x-wave.
This check was corrected.
since ff9f96495b0985c9836ca3585638f2ab471d93c6
=> SF: Fix plotter to sf_assert properly for single text waves as input

Packages/MIES/MIES_WaveDataFolderGetters.ipf
With IP9 the characters allowed for Dimlabels are stricter. For this in 487be1f1f02d390abdf389c78ce4b12761366801
a upconversion was introduced. However, it happened too late in the LBN upgrade chain, such that old DimLabels generated an RTE.
The upconversion was moved to an earlier location in the LBN upgrade process.
=> bugfix: When upgrading the LBN the DimLabels were converted too late

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf, Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/tests/HardwareBasic/UTF_Databrowser.ipf
This fixes the problem with the missing "restore" button once the settings history was closed.
It also fixes the problem that the really helpful SF hooks did not work with the SweepBrowser.
I also cleaned the code up a bit.
=> Fix hooks functions for SweepBrowser

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_WaveBuilder.ipf, Packages/tests/Basic/UTF_WaveBuilderRegression.ipf
The calculation from 80dfc18 (WB_TrigSegment: Use new-style function parameter declaration, 2022-07-18) is wrong.
Redoing the math properly allows us to define a lower and upper bound for
the index of the matches.
We are now also much more confident about the solution, therefore the BUG
messages were upgraded to an assertion.
Close #1536.
=> WB_TrigCalculateInflectionPoints: Fix calculation

Packages/MIES/MIES_GuiUtilities.ipf
This is now a funtion name in the latest UTF version.
=> MIES_GuiUtilities.ipf: Don't use info as wave name

Packages/MIES/MIES_DataBrowser_Macro.ipf, tools/check-code.sh
Broken since 70a3710 (tools/check-code.sh: Check that the list of function prefixes has no duplicates, 2022-11-22).Thanks for opening a PR in MIES :sparkles:!
=> tools/check-code.sh: Make failing test really fail

Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf, Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
This makes the test pass with a slow machine and/or UTF coverage.
=> Tests/CheckTPEntriesFromLBN: Use a larger ITI

Packages/tests/Basic/UTF_Utils.ipf
Introduced in IP9 r39493. Using CLOSE instead of EQUAL also avoids spurious test case errors due to rounding issues.
=> Tests/AcceptsValid10: Adapt to higher DateTime precision

Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
This avoids spurious errors due to the enhanced precision of DateTime introduced in IP9 r39493.
=> NWB_GetFileForExport: Compare session start times with tolerance

Packages/MIES/MIES_GuiUtilities.ipf
Turns out the function only suceeds if a graph window is on top. So let's just created one and dispose it afterwards.
Close: #1577
=> ShowTraceInfoTags: Make it really work

Packages/MIES/MIES_Utilities.ipf
- Retrieving numEntries by calling numpnts created a pending RTE for a null wave argument. The RTE was hidden in the tests because the function is declared threadsafe.
- solution: First check argument with ASSERT_TS before calling numpnts
since a1bc2f34b1e24417a7def6ae76d2f4b38b6a0f4a
=> bugfix for SetStringInWaveNote generating pending RTE

Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf
- With the introduction of shortnames for epochs the epochs operation returned the full tags information instead of the name. However according to the documentation it should only return the name.
=> SF: bugfix for epochs operation not returning name in latest version

Packages/MIES/MIES_WaveBuilder.ipf
Although Igor Pro does also do some floating point comparison magic, we need to use the real deal in this case.
Close #1598
=> WB_TrigCalculateInflectionPoints: Prefer CheckIfClose over plain =

Packages/MIES/MIES_DataBrowser.ipf
This allows for old labnotebooks to be compatible again.
=> DB_UpdateSweepPlot: Upgrade labnotebooks before plotting

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf, Packages/MIES/MIES_BrowserSettingsPanel.ipf
This case was missed in 7f64b0d (BSP_GetLBNWave/SB_GetLBNWave: Generalize
them, 2022-01-06).
=> SB_GetLogbookWave: Derive the datafolder from sweepNumber for LBT_RESULTS

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_Utilities.ipf
Currently the coloring of the notebook commands requires to change the notebook selection. This can interfere quite easily with the user typing. So let's skip coloring the keywords if the contents did not change and only do it on deactivation.
It really is annoying.
=> BSP_SFHelpWindowHook: Interrupt the user less when typing

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_Oscilloscope.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_WaveBuilderPanel.ipf, Packages/tests/Basic/UTF_Utils.ipf
This was only requested for the SweepFormula graphs, but I'm now doing it for all other graphs where we restored axes ranges as well. This made for me the most sense.
=> Keep log mode when restoring axis ranges as well

Packages/MIES/MIES_SweepFormula_Helpers.ipf
- in SFH_GetArgumentAsNumeric
since 075f2ea
=> SF: Fix pending RTE due to wrong format in error msg generation

tools/nwb-read-tests/0001-Support-nwb_version-as-a-fixed-length-string-1669.patch, tools/nwb-read-tests/Dockerfile, tools/nwb-read-tests/nwbv2-read-test.py, tools/nwb-read-tests/run.sh
[0001-Support-nwb_version-as-a-fixed-length-string-1669.patch](https://github.com/AllenInstitute/MIES/files/10999571/0001-Support-nwb_version-as-a-fixed-length-string-1669.patch)
=> tools/nwb-read-tests/run.sh: Update version to 2.3.1

Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf
this blocked compilation of hardware tests
since 9582b4a3
=> SF: TP_Test used deprecated GetMultipleResults replaced by SF_ExecuteFormula

Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_GuiPopupMenuExt.ipf, Packages/MIES/MIES_IgorHooks.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES_Include.ipf, Packages/tests/Basic/UTF_JSONWaveNotes.ipf, Packages/tests/Basic/UTF_Utils.ipf
Change to require latest nightly (39935).
close https://github.com/AllenInstitute/MIES/issues/1658
=> Bugfix for exp save request popup on new exp creation with no previous changes

tools/autorun-test.sh, tools/cleanup-logfiles.sh, tools/gather-logfiles-and-crashdumps.sh
Since b5e648ac (tools/autorun-test.sh: Cleanup logfiles, 2022-12-13) we cleanup logfiles before a CI run of IP. This did fix the issue of accumulating large logfiles.
And since 96af30d6 (UploadCrashDumpsDaily/UploadLogFilesDaily: Do nothing in CI, 2023-03-29) we don't upload the diagnostic/log files anymore in CI.
What we actually want to do with diagnostics and log files is attach them as artefact to the running CI job. This is now implemented by tools/gather-logfiles-and-crashdumps.sh.
Close #1638
=> tools: Gather diagnostics and log files for each CI run with IP

Packages/MIES/MIES_GuiUtilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
GUI getters GetPopupMenuString, GetSetVariableString, GetValDisplayAsString were not aware that ControlInfo can return S_value that is null if the controls value was never set before.
This caused for theses cases a RTE due to the null string being returned. The RTE was not caught and thus pending.
=> Fix for GUI getters returning string through S_value could be null

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf, Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_ExperimentDocumentation.ipf, Packages/MIES/MIES_InputDialog.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/MIES/MIES_TraceUserData.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/PAPlot/UTF_PA_Tests.ipf, Packages/tests/UTF_HardwareHelperFunctions.ipf
close https://github.com/AllenInstitute/MIES/issues/1618
=> Feature/1689 Extend SF operation div for data sets

Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions.ipf
This reverts commit 66a0eee4c (Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions.ipf: Don't run the SC_SpikeControl tests, 2023-01-09).
We can do that because the real crash fix for the tests was ac0946e6 (ITC hardware: Only open and close the ITC device once for a test run, 2023-05-03).
=> Reenable SC_SpikeControl tests

.github/workflows/build-pr.yml
70daa61bd (CI: add GH actions for main and release builds, 2023-04-20)
introduced a zip archive as artifact for deployment for workflows on the
main/release branch. This was dropped after the merge of PR and
main/release workflow in c3a8d873b (CI: Main workflow calls the PR
workflow now, 2023-05-31) which wasn't intended.
Close #1759
=> Fix CI: add missing artifact

Packages/MIES/MIES_AnalysisBrowserMacro.ipf, Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_IVSCC.ipf, Packages/MIES/MIES_Menu.ipf, Packages/MIES/MIES_WaveBuilder_Macro.ipf, Packages/tests/Basic/UTF_Configuration.ipf, Packages/tests/HardwareBasic/UTF_ConfigurationHardware.ipf, Packages/tests/HardwareBasic/UTF_DAEphys.ipf, Packages/tests/UTF_DataGenerators.ipf, Packages/tests/UTF_HelperFunctions.ipf
- Previously we had the optional parameter usePanelTypeFromFile to hint the restore function that the file should have a panel type and a new window of that type if opened before restore.
- This is changed now, such that this optional parameter is discarded. Instead we check if a panel type information is present in the file and create a new window if so.
close https://github.com/AllenInstitute/MIES/issues/1766
Please note, that the wave builder has no panel type. Thus, for restore no new wavebuilder panel is opened automatically as the function can not know. The wave builder is treated as a generic window, where the user must have that window as front window when attempting the configuration restore.
=> Automatize panel type handling on window configuration restore

.github/workflows/build-release.yml, tools/ftp-upload/Dockerfile, tools/ftp-upload/download-files.sh, tools/ftp-upload/upload-files.sh, tools/report-generator/build.sh
Changes:
- Report Generator uses now a different tag format
- Report Generator now uses the pro license
- Coverage reports are generated only for successful builds
- FTP up- and download docker has been updated. It does no longer store the ssl certificate and has some lftp settings preconfigured.
Close #1758
=> More Github Actions improvements

Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
- for IP9+ because wfprintf only supports long strings since
- NumericWaveToList and TextWaveToList use now the same functions
- for 1D and 2D waves only
close https://github.com/AllenInstitute/MIES/issues/1779
=> Speed up TextWaveToList using wfprintf

Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/tests/HistoricData/UTF_HistoricData.ipf, Packages/tests/HistoricData/UTF_HistoricEpochClipping.ipf
After
8c6e5da (EP_WriteEpochInfoIntoSweepSettings: Handle unacquired data, 2021-07-13) we corrected the epoch range calculation that epochs are properly clipped to the sweep range. Older data can contain epochs that have ranges beyond the sweep range.
For that data, we needed a workaround that clips epochs or skips outlier epochs:
- epochs outside the sweep range are skipped
- epochs starting within the sweep and ending outside are clipped before retrieving the sweep data in that range.
Note: the original old epoch data in the LBN is not touched.
close https://github.com/AllenInstitute/MIES/issues/1595
=> SF: bugfix: Add epoch range clipping for SFH_GetSweepsForFormula

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf
Checked: 
close https://github.com/AllenInstitute/MIES/issues/1765
=> Add epoch information for unassociated DA channels + display in DB

Packages/MIES/MIES_MiesUtilities.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf, Packages/tests/UTF_HardwareHelperFunctions.ipf
Also adapted the TTL test UnassociatedChannelsAndTTLs to check against the correct setup.
=> Bugfix AcquireData_NG ignored TTL channels 4-7 in setup for NI HW

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_Structures.ipf, Packages/tests/Basic/UTF_Labnotebook.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
This PR updates the DataConfigurator module to gather more information for TTL channels that are used in [a future PR](https://github.com/AllenInstitute/MIES/pull/1791) to introduce epochs for TTL channels.
Fixes:
- s.numTTLEntries are actually the number of TTL entries now, were wrongly the number of DACEntries until now.
- the saved stim set length in the LNB for TTL were the non-decimated lengths. For all other channel types the decimated lengths are saved, this was also taken over for TTL now
- DC_ITC_MakeTTLWave was called for each rack and gathered some LNB information for all channels on every call
close https://github.com/AllenInstitute/MIES/issues/1796
=> Prepare TTL epochs

Packages/MIES/MIES_DataConfigurator.ipf
Was still using a direct indexed write to the sweepDataLNB.
=> DC: Use DC_DocumentChannelProperty for ITC TTL hardware channel documentation

Packages/MIES/MIES_DataConfigurator.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
previously always DATA_ACQUISITION_MODE was set, which resulted in an attempt to setup a stimset for a activated TTL channel when TP was run. However, there should be no TTL channel setup for TP even when the channel is activated for DAQ.
Since:
0530ff40 (DC: Add more DataConfigurationResult structure fields for TTL and fill them, 2023-07-04)
=> DC: Bugfix Use actual mode DAQOrTP in TTL stimset setup

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/doc/SweepFormula.rst, Packages/tests/Basic/UTF_EpochswoHardware.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf, Packages/tests/UTF_HelperFunctions.ipf
close https://github.com/AllenInstitute/MIES/issues/1817
=> Add TTL support to SF

Packages/MIES/MIES_LogbookViewer.ipf
Broken since 7c3605b7 (Add support displaying textual labnotebook data, 2016-08-18).
It's hilarious how long this was plotted wrongly and nobody noticed.
=> LBV_AddTagsForTextualLBNEntries: Output correct headstage

Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf, Packages/tests/HardwareBasic/UTF_ConfigurationHardware.ipf, Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf, Packages/tests/UTF_Constants.ipf, Packages/tests/UTF_HelperFunctions.ipf
- Previously the on restore the amplifiers were set plain by headstage. The default configuration of the DAEphys panel is that unless "Clear Associations" is clicked all HS are associated. Also MIES implements that associated HS need to have an amplifier set.
On saving the DAEphys window there is no GUI control that state explicitly if a HS is associated or not.
Solution: We assume that the headstages without a set amplifier are unassociated and clear the association for these HS.
since introduction of configuration module
close https://github.com/AllenInstitute/MIES/issues/1763
close https://github.com/AllenInstitute/MIES/issues/1811
=> CONF: Clear HS association on DAEphys window restore for HS w/o amp

Packages/MIES/MIES_GuiUtilities.ipf
Previously the traceinfotags were not reliably activated in the aftercompilehook.
The new approach uses the result of the menu toggle operation DoIgorMenu/OVRD only to determine the actual state of the menu entry. As before a graph window must be open and visible such that the "Graph" menu is present.
Since introduction in:
599e7973 (Add ShowTraceInfoTags, 2021-07-05)
close https://github.com/AllenInstitute/MIES/issues/1577
=> Bugfix for reliable enable of Trace Info tags

.github/workflows/build-release.yml
Report Generation does need the Cobertura files from the instrumentation run. This is not done for release branches and only for the main branch.
See: #1847, PR #1849
=> CI: Disable report generation for release branches [ForwardPort on main]

.github/workflows/build-release.yml
Report Generation does need the Cobertura files from the instrumentation run. This is not done for release branches and only for the main branch.
Close: #1847
=> CI: Disable report generation for release branches

.gitignore, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
Since the bugfix in 3b9e1c5a (bugfix: GetAllFilesRecursivelyFromPath use reliable name retrieval, 2023-05-22) the list of returned files contained an empty entry at the end.
Remove that and also add tests.
=> GetAllFilesRecursivelyFromPath: Fix returning empty results at the end

.github/workflows/build-pr.yml, .github/workflows/test-igor-workflow.yml
=> Add timeout statements for quicker error reporting

Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/MIES/MIES_SweepFormula_PSX.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_Utilities_Checks.ipf, Packages/MIES_Include.ipf, Packages/tests/Basic/UTF_Basic.ipf, Packages/tests/Basic/UTF_Utils.ipf, Packages/tests/Basic/UTF_UtilsChecks.ipf, Packages/tests/UTF_DataGenerators.ipf
=> Extracted parts from #1860

Packages/MIES/MIES_MiesUtilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
We need to handle two different ways to feed in error codes. The first is directly the runtime error code we got from IP. These are unique and for XOPs shifted by 10000 per XOP. The second is V_flag as returned by the XOP with /Z being present. These are the exact same values as defined in the XOP.
The new code handles both cases correctly.
Close #1755
=> ConvertXOPErrorCode: Fix it for the general case

Packages/MIES/MIES_DAEphys.ipf
This reverts commit c17cefc94 (DAP: Use PGC_SetAndActivateControl in DAP_UpdateChanAmpAssignPanel, 2023-07-24).
The reason this does not work is that using PGC calls also the GUI control procedure. But we don't want to call the GUI procedure here as we are syncing from CAA wave to the GUI.
Found as setting pressure devices doesn't work anymore. The hardware pressure controls and the associations controls share the same GUI control procedures DAP_SetVarProc_CAA and DAP_PopMenuProc_CAA and thus using PGC on associations control also triggers a pressure control update.
@MichaelHuth The reverted commit introduced in #1804 broke the pressure device selection. Do you remember why the commit was required?
`runwithOpts(testsuite = "UTF_ConfigurationHardware.ipf")` passes in this branch locally as …
=> DAP_UpdateChanAmpAssignPanel: Don't use PGC_SetAndActivateControl for control setting

Packages/MIES/MIES_MiesUtilities.ipf, Packages/tests/HistoricData/UTF_HistoricData.ipf, Packages/tests/HistoricData/UTF_HistoricDatabrowserChannelCheckboxes.ipf
close https://github.com/AllenInstitute/MIES/issues/1874
=> Fix unchecking sep. TTL in DB causes ASSERTion on ITC hardware if first TTL rack channel is not active

.github/workflows/build-pr.yml, .github/workflows/build-release.yml
Evern since the move to github actions in 70daa61b (CI: add GH actions for main and release builds, 2023-04-20) we just executed the workflows for every branch push.
This can quickly result in the workflow queue being clogged. There is also no point in executing older versions of the same branch when a newer version is available.
The version here supports multiple workflows [1]. And also cancels, on purpose, redundant workflows on main and the release branches. See [2] for a future way to don't do that on special branches.
[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
[2]: https://stackoverflow.com/questions/68418857/how-to-cancel-existing-runs-when-a-new-push-happens-on-githu …
=> .github/workflows: Cancel redundant workflow runs

.github/workflows/build-release.yml
The recent fix in ba69a129 (.github/workflows: Cancel redundant workflow runs, 2023-09-08) did not work for the main branch as the error message on cancelling was [1]:
> Cancelling since a deadlock for concurrency group 'Build Release-refs/heads/main'
> was detected between 'top level workflow' and 'CallPR'
So we now only cancel the CallPR workflow.
=> .github/workflows/build-release.yaml: Fix deadlock on workflow skipping

Packages/MIES/MIES_GuiUtilities.ipf
Under special circumstance DoIgorMenu/OVRD returned a null string for S_value. This was reported to WM and should be fixed in Igor Pro 9 Build 56469 or later.
This commit adds two checks that give a BUG message if S_value is either returned null or empty as both should never happen.
since at least eceba1dd (bugfix for showing the traceinfotags, 2023-08-07)
close https://github.com/AllenInstitute/MIES/issues/1886
=> Bugfix: Fix pending RTE from ShowTraceInfoTags

Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_SweepFormula_PSX.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
Add some commas for some operations
=> Format some code files

tools/sign-installer.sh
We currently have CI issues with signing the installer. The signing step fails very often with:
Run tools/sign-installer.sh -p "***"
Done Adding Additional Store
Number of errors: 1
SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: tools/installer/MIES-Release_2.7_20230809-85-g2be12df50-cis.exe
The causes are unknown.
As a band-aid let's retry the signing step on error.
Close #1904
=> tools/sign-installer.sh: Add retry loop

Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
- When PowerSPectrum is enabled and TP is run then the amplitude should be zero This is now properly checked.
=> Tests: Add TP amplitude check in RunPowerSpectrum testcase

Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_Oscilloscope.ipf, Packages/MIES/MIES_SamplingInterval.ipf, Packages/MIES/MIES_TestPulse.ipf
- there exists hardware that can have different sampling rates for DAC and ADC Thus, the function for determining the sampling interval must depend on the channel type.
- the main utility function changes is DAP_GetSampInt that got a channel type argument added
The scope of this change is only to introduce support in the sample interval getter functions, it does not introduce acquisition support for channel dependent sample rates.
=> SI: Introduce channel type dependent sampling interval (SUTTER preparation 2)

Packages/MIES/MIES_TestPulse.ipf
In the case the test pulse data is completely NaN WaveStats can not determine V_minRowLoc and V_maxRowLoc and returns a -1 in both. This index was used unchecked and resulted in a RTE for invalid wave index access.
This is now checked properly and NaN is returned for "instantaneous".
since
c5ed1686 (TP_TSAnalysis: Change the way we calculate the instantaneous resistance, 2022-09-02)
=> Fix: Testpulse calculation failed if TP data is NaN

.github/workflows/build-pr.yml, .github/workflows/build-release.yml, Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf, Packages/tests/UTF_DataGenerators.ipf, Packages/tests/UTF_TestNWBExportV1.ipf, Packages/tests/UTF_TestNWBExportV2.ipf
-> Look into code, having [0, 7] would be nice.
=> Add testing with ITC1600

.github/workflows/build-pr.yml, .github/workflows/build-release.yml, Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf, Packages/tests/UTF_DataGenerators.ipf, Packages/tests/UTF_TestNWBExportV1.ipf, Packages/tests/UTF_TestNWBExportV2.ipf
Will merge once CI passes and #1900 is approved and merged.
=> Add testing with ITC-1600 [backport]

.github/workflows/build-release.yml
Bug introduced in 6f983d27 (CI: Add testing with ITC1600, 2023-09-25).
=> .github/workflows/build-release.yml: Fix typo in assets name

.github/workflows/build-pr.yml
The compilaton job does not need to depend on the installer job and the tests without hardware job is now executed before the hardware jobs. The reason is that the latter jobs are quite expensive to run.
=> .github/workflows/build-pr.yml: Rework job execution order

Packages/MIES/MIES_MiesUtilities.ipf
This was broken when adding NI support in 7712ba36 (IsValidSweepAndConfig Adapted for new data storage format as WREF wave, 2018-08-07).
=> IsValidSweepWave/IsValidSweepAndConfig: Allow null sweep waves again

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Sub.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Supra.ipf
We want to distinguish the setup of the overrideResults wave per operation mode for PSQ_DAScale in a future commit.
=> PSQ_CreateOverrideResults: Pass in the operation mode for PSQ_DAScale

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/tests/Basic/UTF_Basic.ipf, Packages/tests/Basic/UTF_ThreadsafeDataSharing.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions.ipf, Packages/tests/HardwareBasic/UTF_HardwareBasic.ipf, Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf, Packages/tests/HistoricData/UTF_HistoricData.ipf, Packages/tests/PAPlot/UTF_PAPlot.ipf, Packages/tests/PAPlot/UTF_PA_Tests.ipf, Packages/tests/UTF_HardwareHelperFunctions.ipf, Packages/tests/UTF_HelperFunctions.ipf
<details>
<summary>Done</summary>
</details>
=> Check for free/local wave leaks in CI testing

Packages/MIES/MIES_Logging.ipf, Packages/tests/Basic/UTF_Utils.ipf
The template function LOG_GenerateEntryTemplate had its ts object with the timestamp removed in 2fab915a (LOG_GenerateEntryTemplate: Remove ts object, 2023-05-24). The idea was the don't want to have the timestamp in the template for the log writters in the ITCXOP and the ZeroMQ XOP.
But we forgot that we also use that function via LOG_AddEntry and this needs have a timestamp.
So let's add it back here.
=> LOG_AddEntry: Readd timestamp

.github/workflows/build-pr.yml, .github/workflows/build-release.yml
Failed pipelines might not have NWB files so we need to handle this case gracefully.
Code taken from [1] and checked locally.
[1]: https://superuser.com/a/352387
Close #1951
=> .github/workflows/FTPUpload: Handle missing nwb files gracefully

Packages/MIES/MIES_Logging.ipf, Packages/tests/Basic/UTF_Utils.ipf
The template function LOG_GenerateEntryTemplate had its ts object with the timestamp removed in 2fab915a (LOG_GenerateEntryTemplate: Remove ts object, 2023-05-24). The idea was the don't want to have the timestamp in the template for the log writters in the ITCXOP and the ZeroMQ XOP.
But we forgot that we also use that function via LOG_AddEntry and this needs have a timestamp.
So let's add it back here.
=> [Backport] LOG_AddEntry: Readd timestamp

.github/workflows/build-pr.yml, .github/workflows/build-release.yml, .github/workflows/test-igor-workflow.yml, .pre-commit-config.yaml, tools/ftp-upload/compress-nwb-files.sh
This finally supports download artifacts before the workflow finishes [1].
[1]: https://github.com/actions/toolkit/tree/main/packages/artifact#v2---whats-new
=> .github/workflows: Move to v4 for upload-artifacts

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf
In 76b7cd2f (Patch Seq: Make it work with indexing, 2018-06-11) we introduced support for using indexing with the patch seq analysis functions. We did that by executing the code we can in PRE_SET_EVENT and everything else in PRE_DAQ_EVENT. The added fallthrough means that we execute the code in PRE_SET_EVENT also in PRE_DAQ_EVENT.
It is not clear why we did it back then like that, so let's remove the fallthrough.
Close #1192
The reason I'm doing that now is that I want to perform some more expensive tasks for DAScale adaptive supratreshold in PRE_SET_EVENT but then it matters if we execute that code in PRE_DAQ_EVENT or not.
=> MIES_AnalysisFunctions_PatchSeq.ipf: Remove fallthrough to PRE_SET_EVENT

Packages/MIES/MIES_Epochs.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/tests/HardwareBasic/UTF_Epochs.ipf
The epoch test had the issue that they were targetted for higher DA frequencies like 100 kHz, but sutter runs with 10 kHz.
Thus, some checks were off by one sample, e.g. the amplitude check.
Adapted determination of amplitude boundary checks and TP boundaries.
=> Sutter preparation: Test adaptation for epochs tests to work with Sutter

Packages/tests/Basic/UTF_Basic.ipf, Packages/tests/HistoricData/UTF_HistoricData.ipf, Packages/tests/PAPlot/UTF_PA_Tests.ipf, Packages/tests/UTF_HardwareHelperFunctions.ipf, Packages/tests/UTF_HelperFunctions.ipf
This allows to run tests for local debugging purposes in different igor instances.
Close #1975
=> Tests: Call zeromq_stop after the complete test run

Packages/tests/Basic/UTF_Utils.ipf, Packages/tests/UTF_HelperFunctions.ipf
We should only ignore the lines with {}. And only if we only have these lines can we skip the file.
Added also two more info calls for better debugging.
Bug introduced in ed8a41dc (LOG_AddEntry: Readd timestamp, 2023-12-11).
Close #1970
=> Tests/CheckLogFiles: Fix the test

Packages/tests/UTF_HelperFunctions.ipf
Although 82a4bc59 (AdditionalExperimentCleanup: Handle reopening the debug panel correctly, 2021-12-22) claimed to fix the debug panel closing and reopening properly, it failed to preserve the listbox wave including the selections.
We now do that.
Close #1974
=> Tests/AdditionalExperimentCleanup: Preserve the DebugPanel waves

Packages/MIES/MIES_AnalysisFunctionManagement.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DAEphys_GuiState.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
=> Skip some more function instrumentation

Packages/MIES/MIES_Debugging.ipf
In that way there is no question from which software package the message came.
Close #1992.
=> BUG/BUG_TS: Prefix messages with MIES

Packages/MIES/MIES_SweepFormula_PSX.ipf, Packages/tests/Basic/UTF_SweepFormula_PSX.ipf
@timjarsky Please review and scrutinize
Close #1981
=> Make psx rise time sign dependent on kernel amp sign

Packages/tests/Basic/UTF_SweepFormula_PSX.ipf
Introduced in d1cf16be (PSX_CreateHistogramOfDeconvSweepData: Rework it completely, 2024-01-17).
=> TestOperationPSXTooLargeDecayTau: Fix broken conflict resolution

Packages/MIES/MIES_TestPulse_Single.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf, Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf, ctags.cnf
We always pass zeroDAC = 1 for TP MD so there is no reason to deviate for
single device from that approach.
We also pass the abort on error flag as done in a lot of other call sites
of HW_StopAcq.
Close #1996
Close #1965
=> MIES_TestPulse_Single.ipf: Zero DAC after stopping acquisition

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRheobase.ipf
PSQ_Rheobase does not have a per Sweep QC labnotebok setting. Therefore we decided in 23f0714f (Analysis functions dashboard, 2018-05-06) to use, for passing set QC, the last spiking/non-spiking sweeps as passed and everything else as failed.
Unfortunately it was not anticipated that only two sweeps are present and in that case we have one sweep both failing and passing as Duplicate/RMD clips its passed indices.
By using the set difference we avoid this issue.
Close #2017
=> AD_FillWaves: Fix calculation of failed sweeps for Rheobase

Packages/MIES/MIES_DataAcquisition_Multi.ipf, Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
- there exists a bug in Igor Pro 9 where FIFO2WAVE does not work with ranges of a single point
- These ranges can appear in DAQ however: - If the  background task is called very fast. However due to the 1/60 s minimul rate this is very unlikely and happens in reality basically never
- If the last fifo position is one point before the planned end, i.e. size of the AD channel wave. Then on next readout only one point is read, even if V_FIFOChunks would allow more. This was an approach to minimize copying unnecessary data.
Workaround:
The workaround includes two changes:
1. Readout only if there are at least two new samples in the FIFO.
2. Readout all new samples in the FIFO and then copy only the needed part, specifically at the end of acquisition.
Change 1 guarantees that there are always …
=> bugfix: FIFO2WAVE does not work with single point ranges

.github/workflows/build-pr.yml, .github/workflows/build-release.yml, .github/workflows/test-igor-workflow.yml, tools/ftp-upload/compress-nwb-files.sh
The v4 versions don't use the deprecated Node.js version 16 [1].
[1]: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> .github/workflows: Update actions

Packages/MIES/MIES_LogbookViewer.ipf
The function tried to retrieve valid LBN entries from non-existent result waves
Note on test:
For that case the RTE is only generated by IP when NVAR_SVAR_WAVE_Checking is enabled in the debugger, that implies that the Debugger is enabled. Thus, a test that would catch this wave assignment error would need to enable the debugger and then stop on the critical location.
For CI execution this is no option and thus a test case for that was discarded. It could look like this:
```igorpro
/// @brief This test checks if LBV_PopupExtGetResultsKeys works properly if no result waves are loaded.
///        To check that some sweeps are loaded through the AB.
static Function TestLBVPopupExtGetResultsKeys()
string abWin, sweepBrowsers, win
variable s_enable, s_debugOnError, s_debugOnAbort, …
```
=> LBV: fix uncaught RTE if result waves were not loaded in LBV_PopupExtGetResultsKeys

Packages/MIES/MIES_WaveBuilder.ipf, Packages/tests/Basic/UTF_Utils.ipf
WB_SplitStimsetName was case-sensitive that led to failing on parsing formula stimset names that are by definition lower case.
The effect was that checks on the existence of formula stimsets failed.
since 714a9aa
close #2045
=> WB: fix WB_SplitStimsetName must be case insensitive

Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/tests/Basic/UTF_AnalysisBrowserTest.ipf
AB_LoadWave retrieves the wave from the current DF instead from the given DF after loading before moving the wave to the final destination.
Fix: Use specifically the given DF.
since 97b1252
close https://github.com/AllenInstitute/MIES/issues/2049
=> AB: bugfix AB_LoadWave does not retrieve wave from the correct DF

Packages/MIES/MIES_StimsetAPI.ipf
Bug introduced in ea03d072 (MIES_StimsetAPI.ipf: Add functions for manipulating stimsets, 2021-05-28).
=> MIES_StimsetAPI.ipf: Fix the path to the example file

Packages/MIES/MIES_WaveBuilder.ipf, Packages/tests/Basic/UTF_WaveBuilder.ipf
The WB has an issue, where non-existing stimsets are not treated as needing an update. Thus, combine type stimsets that depend on another stimset being created first can not be created because the other stimset is not being created from the parameter waves.
since 792d0d2
close https://github.com/AllenInstitute/MIES/issues/2060
=> WB: fix recreation of dependent Stimsets from Stimset parameter waves

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_Epochs.ipf, Packages/tests/Basic/UTF_EpochswoHardware.ipf, Packages/tests/HardwareBasic/UTF_Epochs.ipf, Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf
The epoch sorting had two issues:
1. The sorting was alphabetically such that 2.xxx was between 19.xxx and 20.xxx which is incorrect.
2. The function assumed that there is always some remaining rows to cutoff at the end. If that was not the case then the epoch in the last row is deleted.
1. since a2172f0
2. since 4ed816a
close #2046
close #2059
=> EP: fix epoch sorting to be numerically correct

Packages/tests/UTF_HardwareHelperFunctions.ipf
The NI reliability test is running rather slow on the CI machine and exceeds 10 mins timeout for the acquisition. This results in a fail.
From the esitmation of 0.96 acquisition/s of the CI machine, a raise to 1200 s should be enough.
An alternative would be to upgrade the CI machine, as a factor of 2.5 times slower than my 4 year old development machine is questionable. (Also with respect to the time a full CI run takes)
close #2069
=> Increase timeout for acquisition in tests to 20 mins

tools/ftp-upload/Dockerfile
It currently takes around 45 minutes on main, which is most likely due to the large number of files being transferred.
Let's try 10 at a time over all directories.
[1]: https://github.com/AllenInstitute/MIES/actions/runs/8639332642/job/23694913790
=> tools/ftp-upload/Dockerfile: Use parallel transfer mode

tools/ftp-upload/Dockerfile
The CI job using the ftp download/upload does currently fail [1] and that was due to b19387e5 (tools/ftp-upload/Dockerfile: Use parallel transfer mode, 2024-04-11).
Documentation of the FTP server hoster [2] mentions that only up to 8 parallel connections are supported, so let's use 5 which is in the range of 2 to 8.
[1]: https://github.com/AllenInstitute/MIES/actions/runs/8659318873/job/23761414453
[2]: https://www.hosteurope.de/faq/webhosting/hochladen-von-webinhalten-ftp/filezilla-konfigurieren
=> tools/ftp-upload/Dockerfile: User fewer parallel connections

Packages/tests/Basic/UTF_AsynFrameworkTest.ipf
Since the introduction of the tests in 14cd1ff8d6 (Add Async Framework, 2018-09-17) we tried to verify that the execution really happened out of order. The fix in b8ae7c65ce (Asyn: Fix WARN(1) in tests for orderless execution, 2022-11-03) did not fix it though as we actually need to check that the returnOrder array is not ascending.
As the workload in RunGenericWorker already does a randomized workload we feel lucky that it is never sorted and check that.
=> UTF_AsynFrameworkTest.ipf: Correct out-of-order check

Packages/MIES/MIES_AnalysisBrowser.ipf
When no matching waves could be found in the pxp file then AB_LoadDataWrapper causes an assertion because the recursive cleanup of empty DF results in a killed root DF of the loaded DF structure. A following GetListOfObjects was executed unchecked and caused an ASSERT_TS in that case.
Added check for removed DF.
since
23a4086e (RemoveAllEmptyDataFolders: Make it behave more intuitive, 2024-03-06)
=> AB: fix AB_LoadDataWrapper asserts if zero waves were loaded

.github/workflows/build-pr.yml, .github/workflows/build-release.yml, tools/ftp-upload/compress-files.sh
This makes uploading them much faster. And also takes less storage.
=> tools/ftp-upload: Compress the Cobertura/JUNIT reports as well

Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/tests/Basic/UTF_Labnotebook.ipf
Fixes a LNB readout issue that appears if sweep numbers are not consecutively increasing in the LNB due to speculative LNB entries written from analysisfunctions.
=> Bugfix: lnb sweepnumber overlap readout

Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_Async.ipf, Packages/MIES/MIES_DataAcquisition_Multi.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/tests/Basic/UTF_Utils.ipf, Packages/tests/UTF_HelperFunctions.ipf
- changed the API of DeleteWavePoint to accept either a single index value or a numerical wave with indices
- Added tests and adapted tests
- adapted call sites
close #2096
=> Utils: Extend DeleteWavePoint with the option of an indice wave as argument

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_Debugging.ipf, Packages/MIES/MIES_Labnotebook.ipf, Packages/MIES/MIES_LogbookViewer.ipf, Packages/MIES/MIES_MiesUtilities.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf, Packages/tests/HardwareBasic/UTF_Epochs.ipf, Packages/tests/UTF_HelperFunctions.ipf
- PROP_NOT can be set additionally to the other properties and also alone
- PROP_NON_EMPTY and PROP_NOT_MATCHES_VAR_BIT_MASK were removed as these are now obsolete
- adapted the argument checking in FindIndizes
- adapted call sites for FindIndizes that were using now obsolete constants
- added tests for setting PROP_NOT only
- Extended ConvertListToRegexpWithAlternations with required features, added tests
- adapted TestEpochRecreationRemoveUnsupportedUserEpochs
close #2095
=> Utils: Adapt FindIndizes with new property PROP_NOT to invert the matching

Packages/MIES/MIES_Cache.ipf, Packages/MIES/MIES_Debugging.ipf, Packages/tests/Compilation/CompilationTester.ipf
- added utility function EnableWaveCache and DisableWaveCache
When the define is set, all storing attempts and fetching attempts do nothing, i.e. fetching returns a null wave as if there is a cache miss.
When the define is set the cache state is not changed.
close #2090
requires https://github.com/byte-physics/igortest/pull/469
=> Debug: Add define DISABLE_WAVECACHE to disable caching of waves

Packages/MIES/MIES_OptimzedOverlapDistributedAcquisition.ipf
Due to a missing proper rounding to an integer index before using the index in Redimension where internally trunc(index) is used, oodDAQ was cutting off one point too much from the stimset. The effect was that e.g. preceding pulses were shortened by one sample point.
since
d102c07d (Add new data acquisition mode: Optimized overlap distributed acquisition, 2016-08-10)
close #1993
=> OOD: fix for oodDAQ cutting off one point too much from BL trail

Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
This is useful in an upcoming PR #2109 and probably on other locations.
=> Extend GetSetIntersection to return indices of intersecting elements

Packages/MIES/ACL_UserdataEditor.ipf
Igor doesn't allow [semver](https://semver.org/) like versions like `1.0.0.0` and ignores anything after the first floating point number `1.0`.
This is not a bug per se, but it looks cleaner if any invalid characters are removed.
=> Fix version number style of ACL_UserDataEditor.ipf

Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf
- This new function allows to move datasets from array elements one level up
```igorpro
e.g. [dataset(1, 2), dataset(3, 4)] -> dataset([1, 3], [3, 4]) 
e.g. [dataset(1, 2, 3), dataset(4, 5, 6)] -> dataset([1, 4], [2, 5], [3, 6]) 
e.g. [dataset(1, 2), dataset(4, 5), dataset(6, 7)] -> dataset([1, 4, 6], [2, 5, 7]) 
```
Requirements that this is possible are:
- all initial array elements must resolve to datasets
- all dataset waves of the initial array elements must be non-null, have the same size and must be 1d
- all elements of these datasets must be non-null, have the same type and the same size and must be max 3d
- only numeric and text is supported as type, thus the datasets may not contain datasets themselves If none of the requirements are met the input data is returned.
Add this …
=> SFH: Allow a single promotion of datasets to higher level for range specification

Packages/MIES/MIES_Utilities.ipf, Packages/tests/Basic/UTF_Utils.ipf
- both functions did not check properly if the input waves were actually one-dimensional
This check was added as well as tests.
For GetSetDifference it is sufficient if the first wave argument is 1d as the second one is evaluated through FindValue.
=> Utils: Add additional checks to GetSetIntersection, GetSetDifference

Packages/MIES/MIES_Utilities_Numeric.ipf, Packages/tests/Basic/UTF_Utils.ipf
- popcount was not working correctly for negative numbers
- added tests
since 6340df62 (Add function to calculate the population count, 2015-06-28)
=> Utils: fix function popcount for argument < 0

Packages/tests/UTF_HardwareHelperFunctions.ipf
- main branch tests are run with instrumentation and thus, run slower than on a PR It turns out that the reentry for the NI reliability test times out while the acquisition task is still running.
This change increases the timeout from 20 mins to 40 mins.
close #2185
=> Fix: Timeout on NI reliability test causes the test to fail on main branch

Packages/tests/Basic/UTF_Basic.ipf
The refactoring in
1228f739 (Remaining UTF_Utils function refactoring to separate files, 2024-07-18) missed, that the new testsuite also needs to be added to the list for testing.
This commit fixes this.
=> Fix: Add UTF_SweepFormula_Operations.ipf to list of testsuites

Packages/tests/UTF_HardwareHelperFunctions.ipf
Use the new Igortest assertion SKIP_TESTCASE() in AcquireData_NG in the hardware tests if the SUTTER hardware does not fulfill the requirements of the test case, e.g. too many active headstages
This skips the test case.
=> Add SKIP_TESTCASE() for SUTTER hardware if requirements are not met

Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf, Packages/tests/UTF_TestNWBExportV2.ipf
- previously the test checked only against the standard electrode names
- Add test with a custom electrode name set
close https://github.com/AllenInstitute/MIES/issues/2156
=> Adapt nwbv2 export tests to check against custom electrode names

Packages/MIES/MIES_DAEphys.ipf
For some device types like the USB-6001 the AD channel mode is hardcoded. So users need to use a different AD channel so that we can use differential mode.
In a recent debug session this was forgotten by the main developers, so the error message does need enhancement.
=> DAP_CheckPressureSettings: Enhance error message

.github/workflows/build-pr.yml, .github/workflows/test-igor-rebase-exec-workflow.yml
We currently use on.pull_request for running CI on feature branches. This creates a merge commit against the base branch to run the CI against. This means that the git revision of that CI run is not the HEAD of the branch PR but a transient revision.
This is bad for traceability for us, as we sometimes have long-living branches in semi-production.
By using on.push we can avoid these issues.
Close #2117
=> .github/workflows: Prefer on.push

Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_IgorHooks.ipf, Packages/MIES/MIES_MiesUtilities_Logging.ipf
- Logfile splitting was moved to the IgorQuitHook
- Added a message box for the case the splitting takes longer
- fixed special case of no date found when filtering
close #2158 
Close #2211
=> Fix Move logfile splitting / fix special case

Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf, Packages/MIES/MIES_Async.ipf, Packages/MIES/MIES_Cache.ipf, Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_ConversionConstants.ipf, Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_EnhancedWMRoutines.ipf, Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_PressureControl.ipf, Packages/MIES/MIES_ProgrammaticGUIControl.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_Structures.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_SweepFormula_PSX.ipf, Packages/MIES/MIES_Utilities_Algorithm.ipf, Packages/MIES/MIES_Utilities_Debugger.ipf, Packages/MIES/MIES_WaveBuilder.ipf, Packages/MIES/MIES_WaveBuilderPanel.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/MIES/ZeroMQ_Interop.ipf, Packages/MIES/json_functions.ipf
=> Fix documentation for newer doxygen versions

Packages/MIES/MIES_DataConfiguratonRecreation.ipf
The code did not take into account that ZapNaNs can return a null wave.
since
2eaa70d8 (DC: Add function to recreate DataConfigurationResult structure from LNB, 2024-02-21)
=> DCR: fix pending RTE in DCR_RecreateDataConfigurationResultFromLNB_TTL

Packages/MIES/MIES_DataConfiguratonRecreation.ipf
For the case the "TTL channels" entry does not exist in the LNB we already do this. For consistency we should also do this when the LNB entry exists and no TTL channels are enabled.
The missing wave init had no side effect, but its more correct.
=> DCR: Initalise s.TTLList wave with zero elements in case no TTL channels are on

Packages/MIES/MIES_DataConfigurator.ipf, Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
- cleaned up function DC_CheckIfDataWaveHasBorderVals
- use also HW_GetVoltageRange for ITC
- use the same approach for NI and Sutter
- return the proper channel index for NI (was always 0 before)
- adapt user message
close #2214
=> DC: Add BorderVals check for sutter hardware

Packages/MIES/MIES_CheckInstallation.ipf
=> MIES_CheckInstallation.ipf: Update NIDAQ XOP hash

Packages/MIES/MIES_Async.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Structures.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/tests/Basic/UTF_AsynFrameworkTest.ipf, Packages/tests/UTF_DataGenerators.ipf
If a thread was aborted through a regular AbortOnValue this was caught but only a possible RTE was evaluated. Thus, the readout function could not determine if the thread was aborted or not.
Changes:
- The readout function now uses ASYNC_ReadOutStruct as single argument. This allows extensions without changing all function APIs. The structure includes the former values for dfr, RTE code, RTE message and now additionally the V_abortCode. The RTE message must be included here as it has to be retrieved as soon as it happened (in the thread) and needs to be trnasported then to the main thread as well.
- The user readout function can evaluate then both error conditions and react accordingly.
- Tests
close #2252
=> ASYNC: Improved error status transfer from workers to main thread

Packages/Conversion/MIES_MassExperimentProcessing.ipf
The name of the optional parameter has changed in 72cb45a0 (NWB: Create separate NWB file for each device, 2024-08-13).
As the file must be manually activated, we don't do compilation CI for it.
Close #2263
=> MIES_MassExperimentProcessing.ipf: Fix compilation error

Packages/MIES/MIES_Debugging.ipf, Packages/MIES/MIES_ThreadsafeDataSharing.ipf, Packages/tests/Basic/UTF_Debugging.ipf, Packages/tests/Basic/UTF_ThreadsafeDataSharing.ipf, Packages/tests/UTF_HelperFunctions.ipf
Just a draft
Improvements:
- writing a variable now does not reinitializes the named storage causing an additional release of two waves and a recreation of two waves. Due to memory allocation each wave creation causes a global lock.
- fixes the mixed check of data/wv in https://github.com/AllenInstitute/MIES/blob/04d32708c5bf91d7f757895ccc087e8303fcfa75/Packages/MIES/MIES_ThreadsafeDataSharing.ipf#L63
- cleaner API with public ReadVar / WriteVar and private Create / Storage Getter
=> Revision ThreadSafeDataStorage utility functions

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
We only want a single colon (:) when using HFS paths. Bug introduced in b68f43bc (CreateMiesVersion: Add support for MacOSX, 2023-08-25).
Close #2268
=> GetPossiblePathsToGit: Fix paths on windows

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
Tested locally with commenting out the candidates trials.
Close #2268
=> Also look for git in PATH

Packages/MIES/MIES_AnalysisFunctionPrototypes.ipf, Packages/tests/Basic/UTF_AnalysisFunctionPrototypes.ipf, Packages/tests/Basic/UTF_Basic.ipf
A prototype function is used for creating function references (FUNCREF). And this also means they are never called.
Add an assertion to make that clear and also add some tests.
@timjarsky This should make it clearer that these are not the example analysis functions.
=> MIES_AnalysisFunctionPrototypes.ipf: Assert out

Packages/tests/Basic/UTF_AnalysisFunctionPrototypes.ipf
When compiling with instrumentation igortest adds a function to mark the file as instrumented. But as we require all functions in the file to assert out this makes the test case fail with [1]:
0: is false. Assertion "FAIL()" failed in AnalysisFunctionPrototypeTests#CheckThatTheyAllAssertOut (UTF_AnalysisFunctionPrototypes.ipf, line 43)
? Function IUTF_TagFunc_bd1f27ca745da4aa90f393ef89b21e4aa84abb5a97b8b36526b552cdeffad1d2_IGNORE
Therefore we have to remove these tag functions from our function list.
Broken since 2d62af695 (MIES_AnalysisFunctionPrototypes.ipf: Assert out, 2024-10-22).
[1]: https://github.com/AllenInstitute/MIES/actions/runs/11467629096/job/31913142347
Close #2287
Will merge when CI passes.
=> tests/CheckThatTheyAllAssertOut: Ignore igortest marker function

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_MiesUtilities_Logbook.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/tests/Basic/UTF_Labnotebook.ipf
Found while working on #2184. No backport as that is an edgy-edge case.
=> Labnotebook querying: Fix querying the NaN sweep with unknown mode

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf, Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf, Packages/MIES/MIES_DAEphys_GuiState.ipf, Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf, Packages/tests/UserAnalysisFunctions.ipf
=> AFH_LastSweepInSet: Make it available for all and fix it

Packages/doc/developers.rst
We do use a separate tag for ITC1600 testing although we have currently only one machine for it together with the NI hardware.
Bug introduced in f983d27b (CI: Add testing with ITC1600, 2023-09-25).
=> Packages/doc/developers.rst: Add ITC1600 tag

Packages/MIES/MIES_AnalysisFunctionHelpers.ipf, Packages/MIES/MIES_AnalysisFunctions.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/doc/svg/analysis-functions-calls-during-RA-stages.svg, Packages/tests/Basic/UTF_AnalysisFunctionParameters.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Sub.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Supra.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRamp.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRheobase.ipf, Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqSquarePulse.ipf, Packages/tests/UTF_HardwareHelperFunctions.ipf
=> Preparations for detecting out of range SetDaScale

.github/workflows/build-pr.yml, tools/run-ipt.sh
We now name that step "IPT checks" as we also do linting. And this means we should also rename tools/ipt-format.sh.
Close #511
=> CI: Rework ipt format check

Packages/MIES/MIES_SweepFormula_PSX.ipf
We need to always fetch the sweepMap in the sweepbrowser. And not only when we have no device.
Bug introduced in bf10c953a (MIES_SweepFormula_PSX.ipf: Handle sweepbrowser labnotebooks correctly, 2024-10-14).
=> PSX_GenerateComboKey: Fix it for the sweepbrowser

.github/workflows/build-pr.yml, .github/workflows/test-igor-rebase-exec-workflow.yml
=> Backport: Remove colon from job name

tools/nwb-read-tests/Dockerfile
This is another incarnation of [1] where is it unclear how this worked
before. According to documentation not allowing any additional
dependencies fixes the issue.
[1]: https://github.com/pypa/pip/issues/9644
=> tools/nwb-read-tests/Dockerfile: Don't install additional dependencies

Packages/MIES/MIES_Configuration.ipf
This is nicer for the user. Although that folder should always exist.
=> CONF_GetSettingsPath: Create the global settings folder if required

Packages/MIES/MIES_MiesUtilities_Algorithm.ipf, Packages/tests/Basic/UTF_Utils_Mies_Algorithm.ipf
We now bail out if we have PROP_NOT without var or str. And PROP_EMPTY now also always requires neither var nor string.
Close #2323 
=> FindIndizes: Fix argument checking

Packages/MIES/MIES_SweepFormula.ipf
When the windows is moved to the front we now also retrieve it, i.e. move fully into the IP window so that it is always visible.
Found during live testing yesterday.
=> SF_button_sweepFormula_tofront: Retrieve Sweepformula plot window

Packages/MIES/MIES_AnalysisBrowser_SweepBrowser_Export.ipf, Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf, Packages/MIES/MIES_Browser_Plotter.ipf, Packages/MIES/MIES_DAC-Hardware.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DataConfigurator.ipf, Packages/MIES/MIES_LogbookViewer.ipf, Packages/MIES/MIES_MiesUtilities_Checks.ipf, Packages/MIES/MIES_MiesUtilities_GUI.ipf, Packages/MIES/MIES_MiesUtilities_Logbook.ipf, Packages/MIES/MIES_Oscilloscope.ipf, Packages/MIES/MIES_OverlaySweeps.ipf, Packages/MIES/MIES_PulseAveraging.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_TestPulse.ipf, Packages/MIES/MIES_WaveBuilderPanel.ipf, Packages/tests/Basic/UTF_Utils_Checks.ipf, Packages/tests/UTF_TestNWBExportV1.ipf, Packages/tests/UTF_TestNWBExportV2.ipf, tools/check-code.sh
This makes the code clearer.
Close #2212
=> Prefer IsAssociatedChannel and IsValidHeadstage

Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula_Operations.ipf
We need to check each given labnotebook key where the potential wildcard
matches.
Bug introduced in d301352 (SweepFormula labnotebook: Enhance it, 2024-09-10).
=> SF labnotebook: Fix multiple keys with wildcards

Packages/MIES/MIES_Browser_Plotter.ipf, Packages/MIES/MIES_PulseAveraging.ipf
This scales better for different monitor sizes.
Close #2013
=> treewide: Prefer relative font sizes for graphs

Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula_Operations.ipf
Broken since 83713dd90 (SF Implement new select operation, 2024-10-02).
=> SF_OperationTPIterate: Handle non-existing sweep data

Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_AnalysisBrowser_Macro.ipf, Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf, Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_WaveBuilderPanel.ipf
This uses more intuitive shortcuts for selecting multiple cells.
Close #2148
=> Prefer Listbox modes with more natural shortcuts

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf
The function `ExecuteGitForMIESVersion()` contained MacOSX specific code with an invalid break statement. This one doesn't compile, because it wasn't used inside a loop or switch statement and is now replaced with an abort according to the function documentation.
=> MIES_GlobalStringAndVariableAccess.ipf: fix return in mac code

Packages/MIES/MIES_AmplifierInteraction.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DAEphys_Macro.ipf, Packages/tests/HardwareBasic/UTF_DAEphys.ipf
We are currently only syncing MIES to MCC settings when changing the headstage or clamp mode.
But we forgot to sync initially which is required if we don't change headstage or clamp mode.
Bug present since forever.
@timjarsky Found while working on the amplifier state change PUB message.
=> DAEphys: Sync MIES to MCC on checkbox click

Packages/tests/Basic/UTF_PGCSetAndActivateControl.ipf
If the TSDS_BUGCOUNT storage in TUFXOP is not initialized before a test case then the readout in CheckForBugMessage creates the storage. With WaveTracking enabled, e.g. AUTOMATED_TESTING_EXPENSIVE is defined then these waves are counted as wave leak.
The TSDS_BUGCOUNT storage is initialized in AdditionalExperimentCleanup that is called from TestCaseBeginCommon.
The local TEST_CASE_BEGIN_OVERRIDE/TEST_CASE_END_OVERRIDE in UTF_PGCSetAndActivateControl.ipf only called CheckForBugMessage for the END but never TestCaseBeginCommon for the BEGIN.
This results in a wave leak reported for the very first TestCase run if from this TestSuite.
Fix:
Call TestCaseBeginCommon in the local TEST_CASE_BEGIN_OVERRIDE function.
since
0b0032e1 (RunAllTests/PA_Tests: Check for bug messages as well, 2022-07-29)
=> Bugfix: CheckForBugMessage caused WaveLeak if storage not initialized

Packages/MIES/MIES_Menu.ipf, Packages/MIES/MIES_Utilities_GUI.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/MIES/MIES_WaverefBrowser.ipf, Packages/MIES/MIES_WaverefBrowser_Macro.ipf, Packages/MIES_Include.ipf, Packages/tests/UTF_DataGenerators.ipf
A useful extension for debugging.
=> Small tool that allows to browse through wave reference waves from the DataBrowser

Packages/Conversion/MIES_MassExperimentProcessing.ipf, Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_CheckInstallation.ipf, Packages/MIES/MIES_Configuration.ipf, Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_DebugPanel.ipf, Packages/MIES/MIES_MiesUtilities_Uploads.ipf, Packages/MIES/MIES_Utilities_File.ipf, Packages/MIES/MIES_Utilities_JSON.ipf, Packages/MIES/MIES_Utilities_Numeric.ipf, Packages/MIES/MIES_Utilities_WaveHandling.ipf, Packages/tests/Basic/UTF_Utils_File.ipf, Packages/tests/Basic/UTF_Utils_Numeric.ipf, Packages/tests/Basic/UTF_Utils_WaveHandling.ipf, Packages/tests/HardwareBasic/UTF_ConfigurationHardware.ipf, Packages/tests/UTF_DataGenerators.ipf
We used to always perform alias/shortcut handling even when we only look for certain file suffixes.
But we only have to try following these if they can be part of the returned list.
So for the common case of Windows OS and a extension which does not match .lnk we can skip the alias resolving.
When we do have aliases we also first call GetFileFolderInfo and only if we have an alias ResolveAlias again, skipping another GetFileFolderInfo for the case when the pointed to file is not an alias.
This allows to gather 100k files on a 1Gb/s network link in under 60s.
```igorpro
Function Dostuff()
Newpath/O testPath "Y:"
beginfunctionProfiling(testTime = 50000)
string result = getAllfilesRecursivelyFromPath("testPath", extension = ".mp3")
endfunctionProfiling()
printf  "Number of files: %d\r", …
```
=> GetAllFilesRecursivelyFromPath: Speed it up with custom extension

Packages/MIES/MIES_AnalysisBrowser.ipf, Packages/MIES/MIES_AnalysisBrowser_Macro.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_LogbookViewer.ipf, Packages/MIES/MIES_MiesUtilities_Sweep.ipf, Packages/MIES/MIES_NeuroDataWithoutBorders.ipf, Packages/MIES/MIES_Utilities_Time.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
A column was added at the right side of the listbox with the experiment information that shows the time when the sweep was acquired.
Another small empty column was added on the right to reserve space where the vertical scrollbar appears. Otherwise the scrollbar covers information.
The column widths were adjusted such that the horizontal size increase of the AB is minimal.
The version of the AB and listbox wave was increased.
close #2251
=> AB: Add column in experiment information list box for sweep time

Packages/doc/developers.rst
The compile check for each commit in c3e7dc3 (.github/workflows: Add
job to compile test each commit, 2023-12-22) suffers from an issue when
the release branch is empty. In this case we then assume that the branch
in question is forked from the release branch instead of main. This
results in checking all commits in main since the release branch forked
off.
By adding an empty commit to the release branch we can circumvent the
problem.
Close #2426
=> Fix release steps

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf, Packages/tests/HistoricData/UTF_HistoricSweepBrowser.ipf
Since fd5ee28 (SF: Use correct LNB getter in SF_GetTraceColor,
2024-10-04) we require mapIndex to be valid when fetching the labnotebook
for sweep data in SF_GetTraceColor.
But average data was always treated sweep-like but that does not have a
map index. This can also be not easily fixed as it is not clear which mapIndex to use
for sweeps from multiple experiments. Instead we now use the default
average color.
This also makes the metadata entry SF_META_AVERAGED_FIRST_SWEEP obsolete.
Close #2390
=> SF_OperationPowerSpectrum: Fix average option with SweepBrowser data

Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf, Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf
This is an enhancement/fix requested in #2362.
=> SweepFormula: Groups multiple x-axis labels

Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/tests/Basic/UTF_SweepFormula.ipf, Packages/tests/HistoricData/UTF_HistoricSweepBrowser.ipf
Will merge once CI is passed and #2417 is merged.
=> [Backport]  SF_OperationPowerSpectrum: Fix average option with SweepBrowser data

Packages/tests/UTF_HelperFunctions.ipf
@MichaelHuth FYI. This was requested by you.
Will merge once CI passed.
=> Tests/RunWithOpts: Don't require .ipf suffix for test suites

Packages/MIES/MIES_Cache.ipf
As verified using testing and contacting WaveMetrics support, the RMD flag of FindValue makes searching a text wave slower by a factor of three to four. The reason is that the implementation does not assume that the search range could be continuous, therefore it isn't optimized as well.
So let's drop the /RMD flag for this particular case.
=> CA_GetCacheIndex: Don't use RMD for FindValue

.github/workflows/monthly-scheduled.yml
With powershell we have CI failures [1]. And for all other workflows we
also default to bash.
[1]: https://github.com/AllenInstitute/MIES/actions/runs/15988849165/job/45098180247Thanks for opening a PR in MIES :sparkles:!
=> .github/workflows/monthly-scheduled.yml: Use bash as default shell

Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf
- the initial formula gets logged
- the state, laststate, lastcalculation, action gets logged
- error message gets logged
- subsequent parser logs are aggregated in root:SFParserStateLog as text wave. Log Segments are indicated by keyword "**STARTPARSER**" in the TOKEN row. This row stores numbers otherwise.
- easily expandable, e.g. if things like recursionlevel are also required.
close https://github.com/AllenInstitute/MIES/issues/2177
=> SF: Add logging of SF parser states when DEBUGGING_ENABLED is defined

.github/workflows/build-pr.yml, .github/workflows/test-igor-rebase-exec-workflow.yml, .github/workflows/test-igor-workflow.yml, Packages/MIES_Include.ipf, Packages/doc/installation.rst, tools/clean_mies_installation.sh, tools/get-igor-path.sh, tools/installer/installer.nsi
=> Add CI for IP10

Packages/tests/HistoricData/UTF_HistoricAnalysisBrowser.ipf
I could not reproduce the failure. But adding a test sounded like a good idea to start the conversation.
Close #2460
=> UTF_HistoricAnalysisBrowser.ipf: Add test for settings restore

Packages/MIES/MIES_AnalysisBrowser_Macro.ipf, Packages/MIES/MIES_Constants.ipf
When you add on windows UNC path like
\\server\share\folder
in the analysis browser this get's shown as
<??>rver<??>ared<??>older
as Igor Pro treats two backslashes as starting an escape sequence for annotated text.
So let's remove escape code support for this listbox to fix the display issue.
Close #2400
=> AnalysisBrowser: Don't support backslash escape sequences in file/folder listbox

Packages/MIES/MIES_BrowserSettingsPanel.ipf, Packages/MIES/MIES_Constants.ipf, Packages/MIES/MIES_DataBrowser.ipf, Packages/MIES/MIES_DataBrowser_Macro.ipf, Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_SweepFormula.ipf, Packages/MIES/MIES_SweepFormula_Helpers.ipf, Packages/MIES/MIES_WaveDataFolderGetters.ipf, Packages/tests/Basic/UTF_SweepFormula_Operations.ipf, Packages/tests/Basic/UTF_SweepFormula_PSX.ipf, Packages/tests/UTF_HelperFunctions.ipf
- The Notebook is now capable of multiple lines, error messages can be copied and the error text can be formatted
- The status LED was replaced by colored error output text
- Increased DB version to 53
close https://github.com/AllenInstitute/MIES/issues/1624
=> DB: Replace SF error SetVar/status LED with Notebook

Packages/MIES/MIES_MiesUtilities_Uploads.ipf
This was dropped in 2436f40 (GetAllFilesRecursivelyFromPath: Rework it
completely, 2025-04-16) but we do use it for outputting a message to the
user.
=> UploadCrashDumps: Write numFiles/numLogs again

.github/workflows/monthly-scheduled.yml
The version of git on the linux runner is 2.31.1 but the --no-detach is
rather recent (2.47). So let's use the config option instead.
Close #2474
=> monthly-scheduled.yml: Fix invalid option errror

Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
These were the only really buggy tests. All other errors were due to some difference in cabling here on my machines which I've fixed now.
Close #2478
=> CheckTPStorage: Fix invalid /M value for WaveStats

Packages/MIES/MIES_PackageSettings.ipf, Packages/MIES/MIES_WaveBuilderPanel.ipf
We need that to be set. Bug introduced in 91e7dcd
(MIES_PackageSettings.ipf: Enhance it, 2025-07-23).
Will merge once CI passed.
=> PS_RemoveCoordinateSaving: Don't remove the window group

.github/workflows/build-pr.yml, .gitignore, tools/initial-repo-config.sh, tools/run-ipt.sh
We are now independent of the current working directory (CWD). The fixes
are having an absolute path to the config.toml and using the full path
relative to the repository root.
=> tools/run-ipt.sh: Don't require the repository root as CWD

Packages/MIES/MIES_GuiUtilities.ipf, Packages/MIES/MIES_PackageSettings.ipf
When the Display Scaling is something like 125% we would increase the
subwindows on every save/restore cycle. The reason is that the scaling
factor of 72 in PointsToPixel/PixelToPoints is only correct for 100%
scaling. In order to support the panel expansion factor which can make the scaling per panel, we now use the scaling of the panel.
Close #2493
=> PS_ApplyStoredWindowCoordinate: Make it work with non-100% scaling

Packages/MIES/MIES_Menu.ipf
In 89a5194d2a (OpenAboutDialog: Scale the panel and notebook actions correctly, 2020-08-09) we added a rescaling of the original panel sizes and contents. On a recent discussion with Michael Huth, it came up that this code looks fishy as it has hardcoded the 96 (aka 100% scaling).
But that makes sense here as the panel was designed with 100% and then get's resized.
This might not be the best possible code, but it is working.
=> MEN_OpenAboutDialog: Add comment about screen resolution calculations

Packages/MIES/MIES_Configuration.ipf
When setting the stimset path with forward slashes in the JSON configuration HFSPathToNative, and also the more appropriate ParseFilePath(5, "*", 0, 0) do output mixed slashes.
Workaround it with a plain string replacement.
Close #2514
=> CONF_RestoreDAEphys: Don't output mixed forward and backward slashes

Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf, Packages/MIES/MIES_Utilities_File.ipf, Packages/tests/HistoricData/UTF_HistoricDataHelpers.ipf
Igor Pro needs to search for an executable if we don't pass in an absolute path. On some rig machines with ~10 entries in the PATH variable this can take a significant amount of time.
Let's use an absolute path instead. We also do use the COMSPEC environment variable for the unlikely case that Windows is not installed on C:\Windows.
Gathering the MIES version from git now takes 400ms on rig8.
=> treewide: Provide an absolute path for cmd.exe

Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf
Since ce3089dd (Force setting disabled checkboxes during control configuration, 2025-09-15) we also set controls which are disabled with the JSON configuration.
This made the RestoreAndSaveConfiguration test fail [1] as that checks the Passed/Failed checkboxes for the Databrowser dashboard which in turn calls AD_SelectResult.
Teach AD_SelectResult to not do anything without bound device.
[1]: https://github.com/AllenInstitute/MIES/actions/runs/18236758301/job/51935043869
=> AD_SelectResult: Do nothing without bound device

Packages/MIES/MIES_DAEphys.ipf, Packages/MIES/MIES_Publish.ipf, Packages/tests/Basic/UTF_ZeroMQPublishing.ipf
This change will allow the WSE to check the state of the saveTP checkbox before attempting to set it.
=> adding saveTP checkbox check and disabled state to PUB_ClampModeChange
